defmodule Graphene.CarbonComponents.FluidTimePicker do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.CoreComponents

  @doc """
  Component `<cds-fluid-time-picker>` from `./src/components/fluid-time-picker/fluid-time-picker.ts`

  Fluid Time Picker component.

  ## Events

  * `change` - Undocumented
  * `invalid` - Undocumented

  """
  attr :disabled, :boolean, doc: "Specify whether the control is disabled"
  attr :hide_label, :boolean, doc: "Specify whether the label should be hidden"
  attr :invalid, :boolean, doc: "Specify whether the control is currently invalid"
  attr :max_length, :string, doc: "Specify the maximum length of the input value", default: "5"
  attr :name, :string, doc: "Name for the input in FormData"

  attr :pattern, :string,
    doc: "Pattern for input validation",
    default: "(1[012]|[1-9]):[0-5][0-9](\\\\s)?"

  attr :placeholder, :string, doc: "Placeholder text for the input", default: "hh:mm"
  attr :read_only, :boolean, doc: "Specify whether the control should be read-only"
  attr :required, :boolean, doc: "Whether the input is required"

  attr :required_validity_message, :string,
    doc: "Custom message for required validation",
    default: "Please fill out this field."

  attr :size, :string, doc: "Size of the time picker", values: ["sm", "md", "lg"], default: "md"
  attr :type, :string, doc: "Input type", default: "text"
  attr :value, :string, doc: "Value of the input"
  attr :warning, :boolean, doc: "Specify whether the control is in warning state"
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :invalid_text, doc: "The invalid text."
  slot :label_text, doc: "The label text."
  slot :time_picker_select, doc: "Slot for time picker select components."

  slot :validity_message,
    doc:
      "The validity message. If present and non-empty, this input shows the UI of its invalid state."

  slot :warning_text, doc: "The warning text."
  slot :inner_block

  def fluid_time_picker(assigns) do
    CoreComponents.fluid_time_picker(assigns)
  end

  @doc """
  Component `<cds-fluid-time-picker-select>` from `./src/components/fluid-time-picker/fluid-time-picker-select.ts`

  Fluid time picker select.

  ## Events

  * `cds-select-selected` - The name of the custom event fired after an item is selected.

  """
  attr :autofocus, :boolean,
    doc: "Sets the select to be focussed automatically on page load. Defaults to false"

  attr :default_value, :string, doc: "Optionally provide the default value of the select."
  attr :disabled, :boolean, doc: "Controls the disabled state of the select"
  attr :hide_label, :boolean, doc: "Specify whether the label should be hidden, or not"
  attr :id, :string, doc: "ID to link the `label` and `select`"
  attr :inline, :boolean, doc: "Specify whether you want the inline version of this control"
  attr :invalid, :boolean, doc: "Specify if the currently value is invalid."
  attr :invalid_text, :string, doc: "Message which is displayed if the value is invalid."
  attr :is_fluid, :boolean, doc: "Specify whether the textarea is fluid or not"
  attr :multiple, :boolean, doc: "`true` to enable multiple selection."
  attr :name, :string, doc: "Name for the select in the `FormData`"
  attr :pattern, :string, doc: "Pattern to validate the select against for HTML validity checking"
  attr :placeholder, :string, doc: "Value to display when the select has an empty `value`"
  attr :readonly, :boolean, doc: "Controls the readonly state of the select"
  attr :required, :boolean, doc: "Boolean property to set the required status"

  attr :required_validity_message, :string,
    doc: "The special validity message for `required`.",
    default: "Please fill out this field."

  attr :selected_index, :string, doc: "The selected index."
  attr :size, :string, doc: "The input box size.", values: ["sm", "md", "lg", "xl"], default: "md"
  attr :value, :string, doc: "The value of the text area."
  attr :warn, :boolean, doc: "Specify if the currently value is warn."
  attr :warn_text, :string, doc: "Message which is displayed if the value is warn."
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :helper_text, doc: "The helper text."
  slot :label_text, doc: "The label text."

  slot :validity_message,
    doc:
      "The validity message. If present and non-empty, this input shows the UI of its invalid state."

  slot :inner_block

  def fluid_time_picker_select(assigns) do
    CoreComponents.fluid_time_picker_select(assigns)
  end

  @doc """
  Component `<cds-fluid-time-picker-skeleton>` from `./src/components/fluid-time-picker/fluid-time-picker-skeleton.ts`

  Fluid time picker skeleton.


  """
  attr :is_only_two, :boolean, doc: "Specify if there are only two TimePicker elements."
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def fluid_time_picker_skeleton(assigns) do
    CoreComponents.fluid_time_picker_skeleton(assigns)
  end
end
