defmodule Graphene.CarbonComponents.Grid do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.CoreComponents

  @doc """
  Component `<cds-grid>` from `./src/components/grid/grid.ts`

  The grid component.

  Rows are formed implicitly as columns fill the 16-unit span.
  """
  attr :align, :any, doc: "Specify grid alignment. Default is center"

  attr :condensed, :boolean,
    doc:
      "Collapse the gutter to 1px. Useful for fluid layouts.\nRows have 1px of margin between them to match gutter."

  attr :full_width, :boolean, doc: "Remove the default max width that the grid has set"

  attr :narrow, :boolean,
    doc:
      "Container hangs 16px into the gutter. Useful for\ntypographic alignment with and without containers."

  attr :row_gap, :string,
    doc:
      "Row gap spacing token suffix for grid rows (for example \"05\"). Defaults to \"07\" via CSS fallback; \"narrow\" defaults to \"05\" and \"condensed\" defaults to \"gutter\". You can set --graphene-grid-row-gap on a parent to let nested grids inherit.",
    values: [
      nil,
      "gutter",
      "01",
      "02",
      "03",
      "04",
      "05",
      "06",
      "07",
      "08",
      "09",
      "10",
      "11",
      "12",
      "13"
    ]

  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global

  slot :column do
    attr :sm, :string
    attr :md, :string
    attr :lg, :string
    attr :span, :string
    attr :attrs, :map
  end

  slot :inner_block

  def grid(%{column: [_ | _]} = assigns) do
    assigns =
      assigns
      |> assign_new(:align, fn -> nil end)
      |> assign_new(:condensed, fn -> false end)
      |> assign_new(:full_width, fn -> false end)
      |> assign_new(:narrow, fn -> false end)
      |> assign_new(:row_gap, fn -> nil end)

    row_gap_given? =
      assigns
      |> Map.get(:__given__, %{})
      |> Map.has_key?(:row_gap)

    assigns =
      if row_gap_given? do
        assigns
      else
        gap =
          cond do
            assigns[:condensed] -> "gutter"
            assigns[:narrow] -> "05"
            true -> nil
          end

        if gap do
          assign(assigns, :row_gap, gap)
        else
          assigns
        end
      end

    component_attrs =
      Graphene.CodeGen.ComponentAttrs.build_component_attrs(assigns, [
        :align,
        :condensed,
        :full_width,
        :narrow,
        :row_gap
      ])

    assigns = assign(assigns, :component_attrs, component_attrs)

    ~H"""
    <CoreComponents.grid {@component_attrs} {@rest}>
      <%= for column <- @column do %>
        <CoreComponents.column
          sm={column[:sm]}
          md={column[:md]}
          lg={column[:lg]}
          span={column[:span]}
          {column[:attrs] || %{}}
        >
          {render_slot(column)}
        </CoreComponents.column>
      <% end %>
    </CoreComponents.grid>
    """
  end

  def grid(assigns) do
    CoreComponents.grid(assigns)
  end
end
