defmodule Graphene.CarbonComponents.Heading do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.CoreComponents

  @doc """
  Component `<cds-heading>` from `./src/components/heading/heading.ts`

  The heading component


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def heading(assigns) do
    CoreComponents.heading(assigns)
  end
end
