defmodule Graphene.CarbonComponents.ModalBody do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.CoreComponents

  @doc """
  Component `<cds-modal-body>` from `./src/components/modal/modal-body.ts`

  Modal body.


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def modal_body(assigns) do
    CoreComponents.modal_body(assigns)
  end

  @doc """
  Component `<cds-modal-body-content>` from `./src/components/modal/modal-body-content.ts`

  Modal body content


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def modal_body_content(assigns) do
    CoreComponents.modal_body_content(assigns)
  end
end
