defmodule Graphene.CarbonComponents.StructuredListHeaderCell do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.CoreComponents

  @doc """
  Component `<cds-structured-list-header-cell>` from `./src/components/structured-list/structured-list-header-cell.ts`

  Structured list header cell.


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def structured_list_header_cell(assigns) do
    CoreComponents.structured_list_header_cell(assigns)
  end

  @doc """
  Component `<cds-structured-list-header-cell-skeleton>` from `./src/components/structured-list/structured-list-header-cell-skeleton.ts`

  Structured list header cell skeleton.

  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def structured_list_header_cell_skeleton(assigns) do
    CoreComponents.structured_list_header_cell_skeleton(assigns)
  end
end
