defmodule Graphene.CarbonComponents.Table do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.CoreComponents

  @doc """
  Component `<cds-table-batch-actions>` from `./src/components/data-table/table-batch-actions.ts`

  Table batch actions.

  ## Events

  * `cds-table-batch-actions-cancel-clicked` - The custom event fired after the Cancel button is clicked.
  * `cds-table-batch-actions-select-all-clicked` - The custom event fired after the Select all button is clicked.

  """
  attr :active, :boolean, doc: "`true` if this batch actions bar should be active."

  attr :selected_rows_count, :string,
    doc:
      "Numeric representation of the total number of items selected in a table.\nThis number is used to derive the selection message.",
    default: "0"

  attr :size, :string, doc: "The table size.", default: "lg"

  attr :total_rows_count, :string,
    doc:
      "Numeric representation of the total number of items in a table.\nThis number is used in the select all button text\nThis property controls the rendering of the Select all button",
    default: "0"

  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def table_batch_actions(assigns) do
    CoreComponents.table_batch_actions(assigns)
  end

  @doc """
  Component `<cds-table-body>` from `./src/components/data-table/table-body.ts`

  Data table body.


  """
  attr :use_zebra_styles, :boolean,
    doc:
      "TODO: Uncomment when Carbon fully implements sticky header\nSpecify whether the header should be sticky.\nStill experimental: may not work with every combination of table props"

  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def table_body(assigns) do
    CoreComponents.table_body(assigns)
  end

  @doc """
  Component `<cds-table>` from `./src/components/data-table/table.ts`

  Data table.

  ## Events

  * `cds-table-header-cell-sort` - The name of the custom event fired before a new sort direction is set upon a user gesture.
  Cancellation of this event stops the user-initiated change in sort direction.
  * `cds-search` - input
  The name of the custom event fired during search bar input
  * `cds-table-change-selection-all` - The name of the custom event fired before header row is selected/unselected upon a user gesture.
  * `cds-table-row-change-selection` - The name of the custom event fired before a row is selected/unselected upon a user gesture.
  * `cds-table-batch-actions-cancel-clicked` - The name of the custom event fired after the Cancel button is clicked.
  * `cds-table-row-expando-toggled` - The name of the custom event fired after the expanded state of a row is toggled upon a user gesture.
  * `cds-table-row-selected` - The name of the custom event fired after a row has been selected.
  * `cds-table-row-all-selected` - The name of the custom event fired after all rows have been selected.
  * `cds-table-sorted` - The name of the custom event fired after the table has been sorted.
  * `cds-table-filtered` - The name of the custom event fired after the table has been filtered containing remaining rows.

  """
  attr :batch_expansion, :boolean, doc: "`true` if this table should support batch expansion"
  attr :expandable, :boolean, doc: "Specify whether the rows should be able to be expandable"

  attr :filter_rows, :any,
    doc:
      "The method used when filtering the table with the search bar.\nCan be replaced with custom method."

  attr :header_count, :string, doc: "The total headers", default: "0"
  attr :is_selectable, :boolean, doc: "`true` if this table contains selectable rows"
  attr :is_sortable, :boolean, doc: "`true` if this table should support sorting."
  attr :locale, :string, doc: "The table size.", default: "en"

  attr :overflow_menu_on_hover, :boolean,
    doc:
      "Specify whether the overflow menu (if it exists) should be shown always, or only on hover"

  attr :radio, :boolean,
    doc: "Specify whether the control should be a radio button or inline checkbox"

  attr :size, :string,
    doc: "The table size.",
    values: ["xs", "sm", "md", "lg", "xl"],
    default: "lg"

  attr :use_static_width, :boolean,
    doc:
      "TODO: Uncomment when Carbon fully implements sticky header\nSpecify whether the header should be sticky.\nStill experimental: may not work with every combination of table props"

  attr :use_zebra_styles, :boolean, doc: "true to add useZebraStyles striping."
  attr :with_header, :any
  attr :with_row_ai_labels, :boolean, doc: "true if AI Labels are added in the rows"
  attr :with_row_slugs, :boolean, doc: "true if slugs are added in the rows"
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :title, doc: "Title"
  slot :description, doc: "Description"
  slot :toolbar, doc: "Toolbar"
  slot :inner_block

  def table_element(assigns) do
    CoreComponents.table_element(assigns)
  end

  @doc """
  Component `<cds-table-expanded-row>` from `./src/components/data-table/table-expanded-row.ts`

  Table row of collapsible details.


  """
  attr :colspan, :string, doc: "The colspan.", default: "1"
  attr :expanded, :boolean, doc: "`true` if the table row should be expanded."
  attr :filtered, :boolean, doc: "`true` if the table row should be filtered."
  attr :highlighted, :boolean, doc: "`true` if the table row should be highlighted."
  attr :selected, :boolean, doc: "`true` if the previous table row has been selected"
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def table_expanded_row(assigns) do
    CoreComponents.table_expanded_row(assigns)
  end

  @doc """
  Component `<cds-table-head>` from `./src/components/data-table/table-head.ts`

  Data table header.


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def table_head(assigns) do
    CoreComponents.table_head(assigns)
  end

  @doc """
  Component `<cds-table-row>` from `./src/components/data-table/table-row.ts`

  Data table row.

  ## Events

  * `cds-table-row-change-selection` - The custom event fired before this row is selected/unselected upon a user gesture.
  Cancellation of this event stops the user-initiated change in selection.
  * `cds-radio-button-changed` - The name of the custom event fired after this radio button changes its checked state.
  * `cds-checkbox-changed` - The name of the custom event fired after this checkbox changes its checked state.
  * `cds-table-row-expando-beingtoggled` - The name of the custom event fired before the expanded state of this row is being toggled upon a user gesture.
  Cancellation of this event stops the user-initiated action of toggling the expanded state.
  * `cds-table-row-expando-toggled` - The name of the custom event fired after the expanded state of this row is toggled upon a user gesture.

  """
  attr :batch_expansion, :boolean, doc: "`true` if this table should support batch expansion"
  attr :disabled, :boolean, doc: "`true` if this table row should be disabled."
  attr :filtered, :boolean, doc: "`true` if this table row should be filtered out."

  attr :hide_checkbox, :boolean,
    doc:
      "Specify whether the checkbox should be present in the DOM,\nbut invisible and uninteractable."

  attr :highlighted, :boolean, doc: "`true` if the table row should be highlighted."

  attr :overflow_menu_on_hover, :boolean,
    doc:
      "Specify whether the overflow menu (if it exists) should be shown always, or only on hover"

  attr :selected, :boolean, doc: "`true` if this table row should be selected."

  attr :selection_label, :string,
    doc: "The `aria-label` attribute for the `<label>` for selection.",
    default: "Select row"

  attr :selection_name, :string,
    doc:
      "The `name` attribute for the `<input>` for selection.\nIf present, this table row will be a selectable one."

  attr :selection_value, :string, doc: "The `value` attribute for the `<input>` for selection."

  attr :radio, :boolean,
    doc: "Specify whether the control should be a radio button or inline checkbox."

  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def table_row(assigns) do
    CoreComponents.table_row(assigns)
  end

  @doc """
  Component `<cds-table-skeleton>` from `./src/components/data-table/table-skeleton.ts`

  Data table skeleton


  """
  attr :column_count, :string,
    doc: "Specify the number of columns that you want to render in the skeleton state",
    default: "5"

  attr :compact, :boolean,
    doc: "Optionally specify whether you want the Skeleton to be rendered as a compact DataTable"

  attr :row_count, :string,
    doc: "Specify the number of rows that you want to render in the skeleton state",
    default: "5"

  attr :show_header, :boolean,
    doc: "Specify if the table header should be rendered as part of the skeleton.",
    default: true

  attr :show_toolbar, :boolean,
    doc: "Specify if the table toolbar should be rendered as part of the skeleton.",
    default: true

  attr :zebra, :boolean, doc: "true to add useZebraStyles striping."
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def table_skeleton(assigns) do
    CoreComponents.table_skeleton(assigns)
  end

  @doc """
  Renders a static table with Carbon styling.

  Use `table_live/1` for LiveView-aware tables with selection/sorting callbacks.
  """
  attr :id, :string, required: true
  attr :rows, :list, required: true
  attr :row_id, :any, default: nil, doc: "the function for generating the row id"
  attr :row_click, :any, default: nil, doc: "the function for handling phx-click on each row"

  attr :row_item, :any,
    default: &Function.identity/1,
    doc: "the function for mapping each row before calling the :col and :action slots"

  attr :selectable, :boolean, default: false, doc: "enable row selection"
  attr :sortable, :boolean, default: false, doc: "enable sorting UI on header cells"

  attr :selected_ids, :list,
    default: nil,
    doc:
      "selected row ids. When nil, the table keeps its internal selection state. Pass an explicit list to control selection."

  attr :selection_name, :string, default: nil, doc: "name attribute for row selection inputs"
  attr :selection_label, :string, default: "Select row", doc: "aria label for row selection"
  attr :radio, :boolean, default: false, doc: "use radio selection instead of checkboxes"
  attr :size, :string, default: "lg", values: ["xs", "sm", "md", "lg", "xl"], doc: "table size"
  attr :expandable, :boolean, default: false, doc: "enable expandable rows"
  attr :batch_expansion, :boolean, default: false, doc: "enable batch expansion control"

  attr :overflow_menu_on_hover, :boolean,
    default: false,
    doc: "show overflow menu only on hover"

  attr :use_zebra_styles, :boolean, default: true, doc: "enable zebra striping"
  attr :use_static_width, :boolean, default: false, doc: "use static table width"
  attr :with_row_ai_labels, :boolean, default: false, doc: "enable AI labels in rows"
  attr :with_row_slugs, :boolean, default: false, doc: "enable slugs in rows"
  attr :locale, :string, default: "en", doc: "table locale"
  attr :filter_rows, :any, default: nil, doc: "custom filter rows function"

  slot :col, required: true do
    attr :label, :any
  end

  slot :action, doc: "the slot for showing user actions in the last table column"
  slot :title, doc: "table title"
  slot :description, doc: "table description"
  slot :toolbar, doc: "table toolbar contents"

  slot :row_decorator, doc: "content injected before row cells" do
    attr :class, :string
  end

  slot :expanded_row, doc: "content rendered as expanded rows"

  def table(%{rows: _} = assigns) do
    assigns =
      assigns
      |> assign_new(:selection_name, fn -> "#{assigns.id}-selection" end)
      |> assign_new(:selection_label, fn -> "Select row" end)
      |> assign_new(:selectable, fn -> false end)
      |> assign_new(:sortable, fn -> false end)
      |> assign_new(:radio, fn -> false end)
      |> assign_new(:size, fn -> "lg" end)
      |> assign_new(:expandable, fn -> false end)
      |> assign_new(:batch_expansion, fn -> false end)
      |> assign_new(:overflow_menu_on_hover, fn -> false end)
      |> assign_new(:use_zebra_styles, fn -> true end)
      |> assign_new(:use_static_width, fn -> false end)
      |> assign_new(:with_row_ai_labels, fn -> false end)
      |> assign_new(:with_row_slugs, fn -> false end)
      |> assign_new(:locale, fn -> "en" end)
      |> assign(:selected_set, selected_set(assigns.selected_ids))
      |> assign(:effective_selectable, effective_selectable?(assigns))
      |> assign(:effective_sortable, effective_sortable?(assigns))
      |> assign(:effective_expandable, effective_expandable?(assigns))

    ~H"""
    <.table_element
      id={@id}
      size={@size}
      expandable={@effective_expandable}
      batch_expansion={@batch_expansion}
      radio={@radio}
      overflow_menu_on_hover={@overflow_menu_on_hover}
      use_zebra_styles={@use_zebra_styles}
      use_static_width={@use_static_width}
      with_row_ai_labels={@with_row_ai_labels}
      with_row_slugs={@with_row_slugs}
      locale={@locale}
      filter_rows={@filter_rows}
      is_selectable={@effective_selectable}
      is_sortable={@effective_sortable}
    >
      <:title :if={@title != []}>
        <Graphene.CarbonComponents.table_header_title>
          {render_slot(@title)}
        </Graphene.CarbonComponents.table_header_title>
      </:title>
      <:description :if={@description != []}>
        <Graphene.CarbonComponents.table_header_description>
          {render_slot(@description)}
        </Graphene.CarbonComponents.table_header_description>
      </:description>
      <:toolbar :if={@toolbar != []}>{render_slot(@toolbar)}</:toolbar>
      <Graphene.CarbonComponents.table_head>
        <Graphene.CarbonComponents.table_header_row
          selection_name={@effective_selectable && @selection_name}
          selection_label={@effective_selectable && "Select all"}
          hide_checkbox={@radio}
          batch_expansion={@batch_expansion}
        >
          <Graphene.CarbonComponents.table_header_cell
            :for={{col, index} <- Enum.with_index(@col)}
            is_sortable={@effective_sortable}
            data-col-index={index}
          >
            {render_column_label(col[:label])}
          </Graphene.CarbonComponents.table_header_cell>
          <Graphene.CarbonComponents.table_header_cell :if={@action != []}>
            <span class="sr-only">Actions</span>
          </Graphene.CarbonComponents.table_header_cell>
        </Graphene.CarbonComponents.table_header_row>
      </Graphene.CarbonComponents.table_head>
      <Graphene.CarbonComponents.table_body id={@id <> "-body"}>
        <%= for {row, index} <- Enum.with_index(@rows) do %>
          <Graphene.CarbonComponents.table_row
            id={row_dom_id(@row_id, row, index)}
            data-row-id={row_key_string(@row_id, row, index)}
            selected={row_selected?(@selected_set, @row_id, row, index)}
            selection_name={@effective_selectable && @selection_name}
            selection_value={@effective_selectable && row_key_string(@row_id, row, index)}
            selection_label={@effective_selectable && @selection_label}
            radio={@radio}
            batch_expansion={@batch_expansion}
          >
            <%= for decorator <- @row_decorator do %>
              {render_slot(decorator, @row_item.(row))}
            <% end %>
            <Graphene.CarbonComponents.table_cell
              :for={col <- @col}
              phx-click={@row_click && @row_click.(row)}
            >
              <Graphene.CarbonComponents.table_cell_content>
                {render_slot(col, @row_item.(row))}
              </Graphene.CarbonComponents.table_cell_content>
            </Graphene.CarbonComponents.table_cell>
            <Graphene.CarbonComponents.table_cell :if={@action != []}>
              <div>
                <%= for action <- @action do %>
                  {render_slot(action, @row_item.(row))}
                <% end %>
              </div>
            </Graphene.CarbonComponents.table_cell>
          </Graphene.CarbonComponents.table_row>
          <Graphene.CarbonComponents.table_expanded_row :if={@effective_expandable}>
            <%= for expanded <- @expanded_row do %>
              {render_slot(expanded, @row_item.(row))}
            <% end %>
          </Graphene.CarbonComponents.table_expanded_row>
        <% end %>
      </Graphene.CarbonComponents.table_body>
    </.table_element>
    """
  end

  def table(assigns), do: table_element(assigns)

  defp selected_set(nil), do: MapSet.new()

  defp selected_set(ids) do
    ids
    |> Enum.map(&to_string/1)
    |> MapSet.new()
  end

  defp effective_selectable?(assigns) do
    selected_ids = assigns.selected_ids || []
    assigns.selectable || assigns.radio || selected_ids != []
  end

  defp effective_sortable?(assigns), do: assigns.sortable
  defp effective_expandable?(assigns), do: assigns.expandable || assigns.expanded_row != []

  defp row_key(row_id_fun, row, index) do
    key =
      cond do
        is_function(row_id_fun, 1) -> row_id_fun.(row)
        is_nil(row_id_fun) -> Graphene.CarbonComponents.DataTable.Shared.row_id(row)
        true -> index
      end

    if is_nil(key), do: index, else: key
  end

  defp row_key_string(row_id_fun, row, index) do
    row_id_fun
    |> row_key(row, index)
    |> to_string()
  end

  defp row_dom_id(row_id_fun, row, index) do
    row_id_fun
    |> row_key(row, index)
    |> to_string()
  end

  defp row_selected?(selected_set, row_id_fun, row, index) do
    MapSet.member?(selected_set, row_key_string(row_id_fun, row, index))
  end

  defp render_column_label(nil), do: nil
  defp render_column_label(fun) when is_function(fun, 0), do: fun.()
  defp render_column_label(label), do: label
end
