defmodule Graphene.CarbonComponents.Tearsheet do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.CoreComponents

  @doc """
  Component `<cds-tearsheet>` from `./src/components/tearsheet/tearsheet.ts`

  Tearsheet.

  ## Events

  * `cds-tearsheet-beingclosed` - The custom event fired before this tearsheet is being closed upon a user gesture.
  Cancellation of this event stops the user-initiated action of closing this tearsheet.
  * `cds-tearsheet-closed` - The custom event fired after this tearsheet is closed upon a user gesture.

  """
  attr :close_icon_description, :string,
    doc: "Sets the close button icon description",
    default: "Close"

  attr :has_close_icon, :boolean,
    doc:
      "Enable a close icon ('x') in the header area of the tearsheet. By default,\n(when this prop is omitted, or undefined or null) a tearsheet does not\ndisplay a close icon if there are navigation actions (\"transactional\ntearsheet\") and displays one if there are no navigation actions (\"passive\ntearsheet\"), and that behavior can be overridden if required by setting\nthis prop to either true or false."

  attr :influencer_placement, :string,
    doc: "The placement of the influencer section, 'left' or 'right'.",
    values: ["right", "left"],
    default: "right"

  attr :influencer_width, :string,
    doc: "The width of the influencer section, 'narrow' or 'wide'.",
    values: ["narrow", "wide"],
    default: "narrow"

  attr :open, :boolean, doc: "`true` if the tearsheet should be open."

  attr :prevent_close_on_click_outside, :boolean,
    doc: "Prevent closing on click outside of tearsheet"

  attr :selector_initial_focus, :any, doc: "The initial location of focus in the side panel"

  attr :width, :string,
    doc: "The width of the influencer section, 'narrow' or 'wide'.",
    values: ["narrow", "wide"],
    default: "narrow"

  attr :rest, :global
  slot :inner_block

  def tearsheet(assigns) do
    CoreComponents.tearsheet(assigns)
  end
end
