defmodule Graphene.ProductComponents.AboutModal do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-about-modal>` from `./src/components/about-modal/about-modal.ts`

  About Modal.

  ## Events

  * `c4p-about-modal-beingclosed` - The custom event fired before this about modal is being closed upon a user gesture.
  Cancellation of this event stops the user-initiated action of closing this about modal.
  * `c4p-about-modal-closed` - The custom event fired after this about modal is closed upon a user gesture.

  """
  attr :additional_info, :any,
    doc:
      "If you are legally required to display logos of technologies used to build your product you can provide this in the additionalInfo. Additional information will be displayed in the footer."

  attr :close_icon_description, :string,
    doc: "Determines if About Modal is open or not.",
    default: "close"

  attr :content, :any,
    doc:
      "Subhead text providing any relevant product disclaimers including legal information (optional)"

  attr :copyright_text, :any, doc: "Determines if About Modal is open or not."

  attr :links, :any,
    doc:
      "An array of Carbon `Link` component if there are additional information to call out within the card. The about modal should be used to display the product information and not where users go to find help (optional)"

  attr :logo, :any, doc: "A visual symbol used to represent the product."
  attr :open, :boolean, doc: "Determines if About Modal is open or not.", default: true

  attr :title, :any,
    doc:
      "Header text that provides the product name. The IBM Services logo consists of two discrete, but required, elements: the iconic IBM 8-bar logo represented alongside the IBM Services logotype. Please follow these guidelines to ensure proper execution."

  attr :version, :any,
    doc: "Text that provides information on the version number of your product."

  attr :rest, :global
  slot :inner_block

  def about_modal(assigns) do
    ProductCoreComponents.about_modal(assigns)
  end
end
