defmodule Graphene.ProductComponents.BigNumber do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-big-number>` from `./src/components/big-number/big-number.ts`

  Undocumented


  """
  attr :fraction_digits, :string, default: "1"
  attr :loading, :boolean
  attr :locale, :string, default: "en-US"
  attr :percentage, :boolean
  attr :size, :string, values: ["default", "lg", "xl"], default: "default"
  attr :total, :string
  attr :trending, :boolean
  attr :truncate, :boolean, default: true
  attr :value, :string
  attr :rest, :global
  slot :icon_button, doc: "Displays an icon button next to `value`."

  slot :label,
    doc:
      "Header area that displays the label above the value. This slot can be customized to include an info icon and a tooltip for additional context."

  slot :trending_icon,
    doc:
      "Displays an icon indicating trend direction. Can be customized to show a downward arrow when the trend is not upward."

  slot :inner_block

  def big_number(assigns) do
    ProductCoreComponents.big_number(assigns)
  end

  @doc """
  Component `<c4p-big-number-skeleton>` from `./src/components/big-number/big-number-skeleton.ts`

  Undocumented


  """
  attr :size, :string, values: [nil, "default", "lg", "xl"], default: "default"
  attr :rest, :global
  slot :inner_block

  def big_number_skeleton(assigns) do
    ProductCoreComponents.big_number_skeleton(assigns)
  end
end
