defmodule Graphene.ProductComponents.Coachmark do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-coachmark>` from `./src/components/coachmark/coachmark.ts`

  coachmark main component

  ## Events

  * `c4p-coachmark-opened` - The custom event fired when the coachmark is opened.
  This event can be used to perform actions such as focusing elements when the coachmark becomes visible.

  """
  attr :align, :string,
    doc: "Where to render the Coachmark relative to its target.",
    default: "top"

  attr :drop_shadow, :boolean,
    doc: "Specify whether a drop shadow should be rendered on the popover."

  attr :floating, :boolean, doc: "Specifies whether the component is floating or not."

  attr :high_contrast, :boolean,
    doc: "Specify whether the component should be rendered on high-contrast."

  attr :open, :boolean, doc: "Specifies whether the component is currently open."
  attr :position, :any, doc: "Fine tune the position of the target in pixels."
  attr :rest, :global
  slot :trigger, doc: "Trigger element for the coachmark."
  slot :inner_block

  def coachmark(assigns) do
    ProductCoreComponents.coachmark(assigns)
  end

  @doc """
  Component `<c4p-coachmark-beacon>` from `./src/components/coachmark/coachmark-beacon/coachmark-beacon.ts`

  CoachmarkBeacon.

  ## Events

  * `c4p-coachmark-beacon-clicked` - Custom event fired when beacon is clicked

  """
  attr :expanded, :boolean, doc: "specify aria-expanded of beacon"
  attr :id, :string, doc: "id for the coachmark beacon", default: "crypto.randomUUID()"

  attr :kind, :string,
    doc:
      "What style of beacon.\nBEACON_KIND is an enum from the Coachmark and can be used for this value.",
    values: [nil, "default"],
    default: "default"

  attr :label, :string, doc: "The aria label.", default: "Show information"
  attr :rest, :global
  slot :icon, doc: "Custom icon for the beacon."
  slot :inner_block

  def coachmark_beacon(assigns) do
    ProductCoreComponents.coachmark_beacon(assigns)
  end

  @doc """
  Component `<c4p-coachmark-body>` from `./src/components/coachmark/coachmark-body.ts`

  coachmark-body for content body


  """
  attr :rest, :global
  slot :inner_block

  def coachmark_body(assigns) do
    ProductCoreComponents.coachmark_body(assigns)
  end

  @doc """
  Component `<c4p-coachmark-header>` from `./src/components/coachmark/coachmark-header.ts`

  coachmark-header for content header section


  """
  attr :close_icon_description, :string,
    doc: "Tooltip text and aria label for the Close button icon."

  attr :drag_icon_description, :string,
    doc: "Tooltip text and aria label for the Drag button icon."

  attr :rest, :global
  slot :header, doc: "Coachmark header content."
  slot :inner_block

  def coachmark_header(assigns) do
    ProductCoreComponents.coachmark_header(assigns)
  end

  @doc """
  Component `<c4p-coachmark-tagline>` from `./src/components/coachmark/coachmark-tagline/coachmark-tagline.ts`

  DO NOT USE. This component is for the exclusive use
  of other Onboarding components.

  Coachmark tagline component.

  ## Events

  * `c4p-coachmark-tagline-close` - Custom event fired when close button is clicked
  * `c4p-coachmark-tagline-cta-click` - Custom event fired when tagline CTA is clicked

  """
  attr :close_icon_description, :string,
    doc: "Tooltip text and aria label for the Close button icon.",
    default: "Close"

  attr :open, :boolean, doc: "Whether the tagline is open."
  attr :title, :string, doc: "The title of the tagline."
  attr :rest, :global
  slot :inner_block

  def coachmark_tagline(assigns) do
    ProductCoreComponents.coachmark_tagline(assigns)
  end
end
