defmodule Graphene.ProductComponents.FullPageError do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-full-page-error>` from `./src/components/full-page-error/full-page-error.ts`

  FullPageError.


  """
  attr :description, :string, doc: "Sets the description text"
  attr :kind, :any, doc: "Sets what kind of error it is. '404' | '403' | 'custom'"
  attr :label, :string, doc: "Sets the label text", default: "Error Label"
  attr :title, :string, doc: "Sets the title text", default: "Title"
  attr :rest, :global
  slot :inner_block

  def full_page_error(assigns) do
    ProductCoreComponents.full_page_error(assigns)
  end
end
