defmodule Graphene.ProductComponents.GuideBanner do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-guide-banner>` from `./src/components/guide-banner/guide-banner.ts`

  GuideBanner.

  ## Events

  * `c4p-guide-banner-toggle` - Custom event fired when banner is opened
  * `c4p-guide-banner-close` - Custom event fired when banner is closed

  """
  attr :collapse_text, :string
  attr :expand_text, :string
  attr :open, :boolean
  attr :title_text, :string
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :icon, doc: "Guide banner icon."
  slot :header, doc: "Guide banner header content."
  slot :body, doc: "Guide banner body content."
  slot :footer, doc: "Guide banner footer content."
  slot :inner_block

  def guide_banner(assigns) do
    ProductCoreComponents.guide_banner(assigns)
  end

  @doc """
  Component `<c4p-guide-banner-element>` from `./src/components/guide-banner/guide-banner-element.ts`

  GuideBannerElement.


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :title, doc: "Guide banner element title."
  slot :description, doc: "Guide banner element description."
  slot :inner_block

  def guide_banner_element(assigns) do
    ProductCoreComponents.guide_banner_element(assigns)
  end
end
