defmodule Graphene.ProductComponents.InterstitialScreenBody do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-interstitial-screen-body>` from `./src/components/interstitial-screen/interstitial-screen-body.ts`

  interstitial-screen-body for body section

  ## Events

  * `c4p-on-before-step-change` - The name of the custom event fired at the start of  the step change.
  * `c4p-on-after-step-change` - The name of the custom event fired at the end of  the step change.

  """
  attr :slot, :string, default: "body"
  attr :rest, :global
  slot :inner_block

  def interstitial_screen_body(assigns) do
    ProductCoreComponents.interstitial_screen_body(assigns)
  end

  @doc """
  Component `<c4p-interstitial-screen-body-item>` from `./src/components/interstitial-screen/interstitial-screen-body-item.ts`

  interstitial-screen-body-item for body children


  """
  attr :step_title, :string, doc: "This will serve the labels for each step"
  attr :rest, :global
  slot :inner_block

  def interstitial_screen_body_item(assigns) do
    ProductCoreComponents.interstitial_screen_body_item(assigns)
  end
end
