defmodule Graphene.ProductComponents.InterstitialScreen do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-interstitial-screen>` from `./src/components/interstitial-screen/interstitial-screen.ts`

  interstitial-screen main component

  ## Events

  * `c4p-interstitial-opened` - The custom event triggered after loading the component.
  Its event.detail will provide you with carousal api methods for step navigation and method to disable any action button
  *
  * `c4p-interstitial-beingclosed` - The name of the custom event fired before interstitial is being closed upon a user gesture.
  Cancellation of this event stops the user-initiated action of closing the interstitial.
  * `c4p-interstitial-closed` - The name of the custom event fired after this tearsheet is closed upon a user gesture.

  """
  attr :fullscreen, :boolean,
    doc:
      "Specifies whether the component is shown as a full-screen\nexperience, else it is shown as a modal by default."

  attr :open, :boolean, doc: "Specifies whether the component is currently open."
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :header, doc: "Interstitial screen header content."
  slot :body, doc: "Interstitial screen body content."
  slot :footer, doc: "Interstitial screen footer content."
  slot :inner_block

  def interstitial_screen(%{} = assigns) do
    assigns =
      assigns
      |> assign_new(:fullscreen, fn -> false end)
      |> assign_new(:open, fn -> false end)

    assigns =
      assigns
      |> assign_new(:events, fn -> nil end)
      |> assign_new(:rest, fn -> %{} end)

    events =
      case assigns[:events] do
        nil ->
          []

        events when is_map(events) ->
          Map.to_list(events)

        events when is_list(events) ->
          if Enum.all?(events, &match?({_, _}, &1)) do
            events
          else
            Enum.map(events, &{&1, []})
          end

        event ->
          [{event, []}]
      end

    assigns =
      if events == [] do
        assigns
      else
        rest = Map.get(assigns, :rest, %{})
        id = Map.get(rest, :id)
        event_attrs = Graphene.JS.events(events: events, id: id)
        assign(assigns, :rest, Map.merge(rest, event_attrs))
      end

    component_attrs =
      Graphene.CodeGen.ComponentAttrs.build_html_attrs(assigns, [
        {"fullscreen", :fullscreen},
        {"open", :open}
      ])

    assigns = assign(assigns, :component_attrs, component_attrs)

    ~H"""
    <c4p-interstitial-screen {@component_attrs} {@rest}>
      {render_slot(@inner_block)}
      <%= for header <- @header do %>
        {render_slot(header)}
      <% end %>
      <%= for body <- @body do %>
        {render_slot(body)}
      <% end %>
      <%= for footer <- @footer do %>
        {render_slot(footer)}
      <% end %>
    </c4p-interstitial-screen>
    """
  end

  def interstitial_screen(assigns) do
    ProductCoreComponents.interstitial_screen(assigns)
  end

  @doc """
  Component `<c4p-interstitial-screen-footer>` from `./src/components/interstitial-screen/interstitial-screen-footer.ts`

  interstitial-screen-footer for footer section

  ## Events

  * `c4p-on-action` - The name of the custom event fired just before the action. You can use this event to perform any async/sync validation.
  if you pass async-action = true, the component will wait for an external listener (e.g., a form validation or confirmation modal) to resolve the proceed()
  callback before continuing. When asyncAction is true, you must listen for the eventOnBeforeAction event and call the proceed() function
  (either synchronously or with a promise) to allow navigation.

  """
  attr :async_action, :any,
    doc:
      "Enables support for asynchronous validation or user confirmation before proceeding\nto the next interstitial step. When set to true, the component will wait for an external\n listener (e.g., a form validation or confirmation modal) to resolve the proceed() callback before continuing.\nWhen asyncAction is true, you must listen for the eventOnBeforeAction event and\ncall the proceed() function (either synchronously or with a promise) to allow navigation."

  attr :next_button_label, :string, doc: "The label for the Next button.", default: "Next"
  attr :previous_button_label, :string, doc: "The label for the Previous button.", default: "Back"
  attr :skip_button_label, :string, doc: "The label for the skip button.", default: "Skip"
  attr :slot, :string, default: "footer"

  attr :start_button_label, :string,
    doc: "The label for the start button.",
    default: "Get Started"

  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def interstitial_screen_footer(assigns) do
    ProductCoreComponents.interstitial_screen_footer(assigns)
  end

  @doc """
  Component `<c4p-interstitial-screen-header>` from `./src/components/interstitial-screen/interstitial-screen-header.ts`

  interstitial-screen-header for header section


  """
  attr :close_icon_description, :string,
    doc: "Tooltip text and aria label for the Close button icon.",
    default: "Close"

  attr :header_subtitle, :string, doc: "Tooltip text and aria label for the Close button icon."
  attr :header_title, :string, doc: "Provide an optional title to be applied to the header."

  attr :hide_progress_indicator, :boolean,
    doc: "Optional parameter to hide the progress indicator when multiple steps are used."

  attr :slot, :string, default: "header"
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def interstitial_screen_header(assigns) do
    ProductCoreComponents.interstitial_screen_header(assigns)
  end
end
