defmodule Graphene.ProductComponents.OptionsTile do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-options-tile>` from `./src/components/options-tile/options-tile.ts`

  OptionsTile.

  ## Events

  * `c4p-options-tile-open` - Custom event fired when tile is opened
  * `c4p-options-tile-close` - Custom event fired when tile is closed

  """
  attr :default_open, :boolean, doc: "Determines if the tile is open by default"

  attr :size, :string,
    doc: "Determines the size of the header",
    values: [nil, "lg", "xl"],
    default: "lg"

  attr :title_id, :string, doc: "ID for the title"
  attr :title_text, :string, doc: "Text for the title"
  attr :rest, :global
  slot :summary, doc: "Summary content for the options tile."
  slot :body, doc: "Body content for the options tile."
  slot :toggle, doc: "Toggle action content for the options tile."
  slot :inner_block

  def options_tile(assigns) do
    ProductCoreComponents.options_tile(assigns)
  end
end
