defmodule Graphene.ProductComponents.PageHeader do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-page-header>` from `./src/components/page-header/page-header.ts`

  Page header.


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def page_header(assigns) do
    ProductCoreComponents.page_header(assigns)
  end

  @doc """
  Component `<c4p-page-header-breadcrumb>` from `./src/components/page-header/page-header-breadcrumb.ts`

  Page header Breadcrumb Bar.


  """
  attr :border, :boolean, doc: "Specify if breadcrumb bar has bottom border.", default: true

  attr :content_actions_flush, :boolean,
    doc: "Set to `true` if content actions should be flush (no padding)"

  attr :page_actions_flush, :boolean,
    doc: "Set to `true` if page actions should be flush (no padding)"

  attr :within_grid, :boolean,
    doc:
      "Set to `true` if the breadcrumb bar is sitting within a grid\n(ie. when used in tandem with page-header-hero-image)"

  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :icon, doc: "Breadcrumb icon slot."
  slot :content_actions, doc: "Content actions slot."
  slot :page_actions, doc: "Page actions slot."
  slot :inner_block

  def page_header_breadcrumb(assigns) do
    ProductCoreComponents.page_header_breadcrumb(assigns)
  end

  @doc """
  Component `<c4p-page-header-hero-image>` from `./src/components/page-header/page-header-hero-image.ts`

  Page header Hero Image.


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def page_header_hero_image(assigns) do
    ProductCoreComponents.page_header_hero_image(assigns)
  end

  @doc """
  Component `<c4p-page-header-scroller>` from `./src/components/page-header/page-header-scroller.ts`

  Page header Scroller button


  """
  attr :align, :string,
    doc: "Specify how the trigger should align with the tooltip",
    default: "top"

  attr :autoalign, :boolean,
    doc: "Specify whether a auto align functionality should be applied",
    default: true

  attr :close_on_activation, :boolean,
    doc:
      "Determines whether the tooltip should close when inner content is activated (click, Enter or Space)",
    default: true

  attr :collapse_text, :string,
    doc: "Specify the collapse text for the scroller button",
    default: "Collapse"

  attr :default_open, :boolean,
    doc: "Specify whether the tooltip should be open when it first renders"

  attr :enter_delay_ms, :string,
    doc: "Specify the duration in milliseconds to delay before displaying the tooltip",
    default: "100"

  attr :expand_text, :string,
    doc: "Specify the expand text for the scroller button",
    default: "Expand"

  attr :leave_delay_ms, :string,
    doc: "Specify the duration in milliseconds to delay before hiding the tooltip",
    default: "300"

  attr :size, :string, doc: "Specify the size of the Button. Defaults to `md`.", default: "md"
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :tooltip_content, doc: "Tooltip content slot."
  slot :inner_block

  def page_header_scroller(assigns) do
    ProductCoreComponents.page_header_scroller(assigns)
  end

  @doc """
  Component `<c4p-page-header-tabs>` from `./src/components/page-header/page-header-tabs.ts`

  Page header Tabs Bar.


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :tags, doc: "Tags slot for the tab bar."
  slot :scroller, doc: "Scroller slot for the tab bar."
  slot :inner_block

  def page_header_tabs(assigns) do
    ProductCoreComponents.page_header_tabs(assigns)
  end

  @doc """
  Component `<c4p-page-header-title-breadcrumb>` from `./src/components/page-header/page-header-title-breadcrumb.ts`

  Page header Title Breadcrumb


  """
  attr :events, :any, default: nil, doc: "custom events passed to Graphene.JS.events/1"
  attr :rest, :global
  slot :inner_block

  def page_header_title_breadcrumb(assigns) do
    ProductCoreComponents.page_header_title_breadcrumb(assigns)
  end
end
