defmodule Graphene.ProductComponents.TruncatedText do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-truncated-text>` from `./src/components/truncated-text/truncated-text.ts`

  TruncatedText.


  """
  attr :align, :string,
    doc: "Specify how the tooltip should align with the content.",
    default: "top"

  attr :autoalign, :boolean, doc: "Specify whether a auto align functionality should be applied"
  attr :collapse_label, :string, doc: "The label on the collapse button."
  attr :expand_label, :string, doc: "The label on expand button."
  attr :id, :string, doc: "Unique identifier for the element."

  attr :lines, :string,
    doc: "The maximum number of lines to display before truncation.",
    default: "0"

  attr :type, :string,
    doc:
      "The method to display the full text when truncated. Options are \"tooltip\" or \"expand\". if not passed, the text would just be truncated with ellipsis.",
    values: ["tooltip", "expand"],
    default: "tooltip"

  attr :value, :string, doc: "The string value to be truncated."
  attr :rest, :global
  slot :inner_block

  def truncated_text(assigns) do
    ProductCoreComponents.truncated_text(assigns)
  end
end
