defmodule Graphene.ProductComponents.UserAvatar do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.ProductCoreComponents

  @doc """
  Component `<c4p-user-avatar>` from `./src/components/user-avatar/user-avatar.ts`

  Useravatar.


  """
  attr :background_color, :string,
    doc: "Provide the background color need to be set for UserAvatar.",
    default: "order-1-cyan"

  attr :image, :any,
    doc: "When passing the image prop, supply a full path to the image to be displayed."

  attr :image_description, :any,
    doc:
      "When passing the image prop use the imageDescription prop to describe the image for screen reader."

  attr :name, :any,
    doc:
      "When passing the name prop, either send the initials to be used or the user's full name. The first two capital letters of the user's name will be used as the name."

  attr :size, :any, doc: "Set the size of the avatar circle"
  attr :theme, :any, doc: "Set theme in which the component will be rendered."

  attr :tooltip_alignment, :string,
    doc: "Specify the alignment of the tooltip.",
    default: "bottom"

  attr :tooltip_text, :any, doc: "Specify the text of the tooltip.\nCan be string"
  attr :rest, :global
  slot :rendericon, doc: "Custom icon slot for the avatar."
  slot :inner_block

  def user_avatar(assigns) do
    ProductCoreComponents.user_avatar(assigns)
  end
end
