defmodule <%= assigns[:module] %> do
  @moduledoc """
  Graphene.CarbonComponents is autogenerated from Carbon web components metadata.

  High-level Carbon components built on top of internal low-level components.

  These wrappers avoid direct use of <cds-*> tags and expose a single
  namespace for Carbon web components. Component implementations live in
  grouped modules under Graphene.CarbonComponents.* and this module
  delegates to them.
  """

  use Phoenix.Component

  alias Graphene.CarbonComponents.DataTableComponent
  alias Graphene.Internal.FormComponents

  defmacro __using__(_opts) do
    quote do
<%= assigns[:custom_imports] %>
<%= assigns[:imports] %>
    end
  end

  <%= assigns[:delegates] %>

  <%= assigns[:custom_components] %>
end
