defmodule <%= @module %> do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  def version(), do: ~S|<%= @version %>|

  defp normalize_events(nil), do: []

  defp normalize_events(events) when is_map(events) do
    Map.to_list(events)
  end

  defp normalize_events(events) when is_list(events) do
    if Enum.all?(events, &match?({_, _}, &1)) do
      events
    else
      Enum.map(events, &{&1, []})
    end
  end

  defp normalize_events(event), do: [{event, []}]

  defp apply_events(assigns) do
    assigns = assign_new(assigns, :events, fn -> nil end)
    events = normalize_events(assigns[:events])

    if events == [] do
      assigns
    else
      rest = Map.get(assigns, :rest, %{})
      id = Map.get(assigns, :id) || Map.get(rest, :id)
      event_attrs = Graphene.JS.events(events: events, id: id)
      assign(assigns, :rest, Map.merge(rest, event_attrs))
    end
  end

  <%= for component <- @components do %>
  <%= Graphene.CodeGen.Component.display component %>
  <% end %>

  defp merge_rest_class(assigns, class_name) do
    rest = Map.get(assigns, :rest, %{})
    class_value = merge_class_value(Map.get(rest, :class), class_name)
    rest = Map.put(rest, :class, class_value)
    assign(assigns, :rest, rest)
  end

  defp merge_rest_class_if(assigns, condition, class_name) do
    if condition, do: merge_rest_class(assigns, class_name), else: assigns
  end

  defp merge_class_value(nil, class_name), do: class_name
  defp merge_class_value("", class_name), do: class_name

  defp merge_class_value(class_value, class_name) when is_list(class_value) do
    class_value
    |> Enum.map(&to_string/1)
    |> Enum.join(" ")
    |> merge_class_value(class_name)
  end

  defp merge_class_value(class_value, class_name) when is_binary(class_value) do
    if String.contains?(class_value, class_name) do
      class_value
    else
      class_value <> " " <> class_name
    end
  end

  defp merge_class_value(_class_value, class_name), do: class_name

  def available_components() do
    [<%= for component <- @components do %><%= inspect(component.componentname) %>, <% end %>]
  end
end
