defmodule <%= assigns[:module] %> do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  alias Graphene.Internal.CoreComponents

  <%= assigns[:helpers] %>

  <%= assigns[:wrappers] %>
end
