defmodule <%= @module %> do
  @moduledoc """
  This module provides pattern matching to retrieve icons sources.

  * Icon name should be atom `icon_name`
  * Size should be one of [16, 20, 24, 32]

  ## Important
  Module is autogenerated, do not edit it directly.
  """
  def version(), do: ~S|<%= @version %>|
  def available_sizes(), do: [16, 20, 24, 32]
  def available_icons(), do: [<%= for icon <- @icons do %>"<%= icon.name %>", <% end %>]
  def icon_raw(icon_name, size)
      when is_binary(icon_name) and size in [16, 20, 24, 32] do
    case {icon_name, size} do
    <%= for icon <- @icons do %>
      <%= for variant <- icon.variants do %>
      {~S|<%= icon.name %>|, <%= variant.size %>} -> %{viewBox: ~S|<%= variant.view_box %>|, content: ~S|<%= variant.content %>| }
      <% end %>
      {~S|<%= icon.name %>|, _} -> %{viewBox: ~S|<%= icon.default.view_box %>|, content: ~S|<%= icon.default.content %>| }
    <% end %>
    end
  end
end
