defmodule <%= assigns[:module] %> do
  @moduledoc """
  Autogenerated module. Do not edit directly.

  Graphene.ProductComponents is autogenerated from IBM Products web components metadata.

  High-level Product components built on top of internal low-level components.

  These wrappers avoid direct use of <c4p-*> tags and expose a single
  namespace for IBM Products web components. Component implementations live in
  grouped modules under Graphene.ProductComponents.* and this module
  delegates to them.
  """

  use Phoenix.Component

  defmacro __using__(_opts) do
    quote do
<%= assigns[:imports] %>
    end
  end

  <%= assigns[:delegates] %>

  <%= assigns[:custom_components] %>
end
