defmodule Graphene.CodeGen.Component.AttrType do
  # TODO: fill this with autogenerated code somehow
  defstruct kind: :any, values: nil

  def new(name) do
    # map js types from custom-elements.json to attr types
    # fallback to type :any in case nothing specific is found
    name = to_string(name)
    cleanname = String.replace(name, "| undefined", "") |> String.trim()
    undefined? = String.contains?(name, "undefined")

    info =
      case cleanname do
        "array" ->
          %{kind: :list}

        "string" ->
          %{kind: :string}

        "number" ->
          %{kind: :string}

        "boolean" ->
          %{kind: :boolean}

        "ACCORDION_ALIGNMENT" ->
          # @carbon/web-components/es/components/accordion/defs.d.ts
          %{kind: :string, values: ~w(start end)}

        "ACCORDION_SIZE" ->
          # @carbon/web-components/es/components/accordion/defs.d.ts
          %{kind: :string, values: ~w(sm md lg)}

        "BUTTON_KIND" ->
          # @carbon/web-components/es/components/icon-button/defs.d.ts
          %{
            kind: :string,
            values: ~w(primary secondary tertiary danger danger--tertiary danger--ghost ghost)
          }

        "BUTTON_SIZE" ->
          # @carbon/web-components/es/components/icon-button/defs.d.ts
          %{kind: :string, values: ~w(sm md lg xl 2xl)}

        "BUTTON_TOOLTIP_ALIGNMENT" ->
          # @carbon/web-components/es/components/icon-button/defs.d.ts
          %{kind: :string, values: ["left", "right", ""]}

        "BUTTON_TOOLTIP_POSITION" ->
          # @carbon/web-components/es/components/icon-button/defs.d.ts
          %{kind: :string, values: ~w(top bottom right left)}

        "BUTTON_TYPE" ->
          # @carbon/web-components/es/components/icon-button/defs.d.ts
          %{kind: :string, values: ~w(button reset submit)}

        "CHAT_BUTTON_SIZE" ->
          # @carbon/web-components/es/components/chat-button/defs.d.ts
          %{kind: :string, values: ~w(sm md lg)}

        "CODE_SNIPPET_TYPE" ->
          # @carbon/web-components/es/components/code-snippet/defs.d.ts
          %{kind: :string, values: ~w(single inline multi)}

        "CONTENT_SWITCHER_SIZE" ->
          # @carbon/web-components/es/components/content-switcher/defs.d.ts
          %{kind: :string, values: ~w(sm md lg xl)}

        "DATE_PICKER_INPUT_KIND" ->
          # @carbon/web-components/es/components/date-picker/defs.d.ts
          %{kind: :string, values: ~w(simple single from to)}

        "DROPDOWN_DIRECTION" ->
          # @carbon/web-components/es/components/dropdown/defs.d.ts
          %{kind: :string, values: ~w(top bottom)}

        "DROPDOWN_SIZE" ->
          # @carbon/web-components/es/components/dropdown/defs.d.ts
          %{kind: :string, values: ~w(sm md lg)}

        "DROPDOWN_TYPE" ->
          # @carbon/web-components/es/components/dropdown/defs.d.ts
          %{kind: :string, values: ["", "inline"]}

        "FILE_UPLOADER_ITEM_SIZE" ->
          # @carbon/web-components/es/components/file-uploader/defs.d.ts
          %{kind: :string, values: ~w(sm md lg)}

        "FILE_UPLOADER_ITEM_STATE" ->
          # @carbon/web-components/es/components/file-uploader/defs.d.ts
          %{kind: :string, values: ~w(uploading complete edit)}

        "FLOATING_MENU_DIRECTION" ->
          # @carbon/web-components/es/components/floating-menu/defs.d.ts
          %{kind: :string, values: ~w(top bottom)}

        "FORM_ELEMENT_COLOR_SCHEME" ->
          # @carbon/web-components/es/globals/shared-enums.d.ts
          %{kind: :string, values: ["", "light"]}

        "INLINE_LOADING_STATE" ->
          # @carbon/web-components/es/components/inline-loading/defs.d.ts
          %{kind: :string, values: ~w(inactive active finished error)}

        "INPUT_TYPE" ->
          # @carbon/web-components/es/components/text-input/defs.d.ts
          %{kind: :string, values: ~w(email password tel text url)}

        "INPUT_TOOLTIP_ALIGNMENT" ->
          # @carbon/web-components/es/components/text-input/defs.d.ts
          %{kind: :string, values: ~w(start center end)}

        "INPUT_TOOLTIP_DIRECTION" ->
          # @carbon/web-components/es/components/text-input/defs.d.ts
          %{kind: :string, values: ~w(top right bottom left)}

        "GRID_ROW_GAP" ->
          # Carbon spacing token suffixes used for row gaps
          %{kind: :string, values: ~w(gutter 01 02 03 04 05 06 07 08 09 10 11 12 13)}

        "LOADING_TYPE" ->
          # @carbon/web-components/es/components/loading/defs.d.ts
          %{kind: :string, values: ~w(regular small)}

        "MODAL_SIZE" ->
          # @carbon/web-components/es/components/modal/defs.d.ts
          %{kind: :string, values: ~w(xs sm md lg)}

        "NOTIFICATION_KIND" ->
          # @carbon/web-components/es/components/notification/defs.d.ts
          %{kind: :string, values: ~w(success info info-square warning warning-alt error)}

        "OVERFLOW_MENU_SIZE" ->
          # @carbon/web-components/es/components/overflow-menu/defs.d.ts
          %{kind: :string, values: ~w(sm md lg)}

        "PAGINATION_SIZE" ->
          # @carbon/web-components/es/components/pagination/defs.d.ts
          %{kind: :string, values: ~w(sm md lg)}

        "POPOVER_ALIGNMENT" ->
          # @carbon/web-components/es/components/popover/defs.d.ts
          # excluded deprecated
          %{
            kind: :string,
            values:
              ~w(top top-start top-end bottom bottom-start bottom-end left left-start left-end right right-start right-end)
          }

        "PROGRESS_BAR_SIZE" ->
          # @carbon/web-components/es/components/progress-bar/defs.d.ts
          %{kind: :string, values: ~w(small big)}

        "PROGRESS_BAR_STATUS" ->
          # @carbon/web-components/es/components/progress-bar/defs.d.ts
          %{kind: :string, values: ~w(active finished error)}

        "PROGRESS_BAR_TYPE" ->
          # @carbon/web-components/es/components/progress-bar/defs.d.ts
          %{kind: :string, values: ~w(default inline indented)}

        "MENU_SIZE" ->
          # @carbon/web-components/es/components/menu/defs.d.ts
          %{kind: :string, values: ~w(xs sm md lg)}

        "PROGRESS_STEP_STAT" ->
          # @carbon/web-components/es/components/progress-bar/defs.d.ts
          %{kind: :string, values: ~w(complete current incomplete invalid)}

        "RADIO_BUTTON_LABEL_POSITION" ->
          # @carbon/web-components/es/components/radio-button/defs.d.ts
          %{kind: :string, values: ~w(left right)}

        "RADIO_BUTTON_ORIENTATION" ->
          # @carbon/web-components/es/components/radio-button/defs.d.ts
          %{kind: :string, values: ~w(horizontal vertical)}

        "SELECTION_FEEDBACK_OPTION" ->
          # @carbon/web-components/es/components/multi-select/defs.d.ts
          %{kind: :string, values: ~w(fixed top top-after-reopen)}

        "SIDE_NAV_COLLAPSE_MODE" ->
          # @carbon/web-components/es/components/ui-shell/defs.d.ts
          %{kind: :string, values: ~w(fixed rail responsive)}

        "SIDE_PANEL_PLACEMENT" ->
          # @carbon/web-components/es/components/side-panel/defs.d.ts
          %{kind: :string, values: ~w(right left)}

        "SIDE_PANEL_SIZE" ->
          # @carbon/web-components/es/components/side-panel/defs.d.ts
          %{kind: :string, values: ~w(xs sm md lg 2xl)}

        "SKELETON_TEXT_TYPE" ->
          # @carbon/web-components/es/components/skeleton-text/defs.d.ts
          %{kind: :string, values: ["", "heading"]}

        "SLUG_KIND" ->
          # @carbon/web-components/es/components/slug/defs.d.ts
          %{kind: :string, values: ["", "inline"]}

        "SLUG_SIZE" ->
          # @carbon/web-components/es/components/slug/defs.d.ts
          %{kind: :string, values: ~w(mini 2xs xs sm md lg xl)}

        "STACK_ORIENTATION" ->
          # @carbon/web-components/es/components/stack/defs.d.ts
          %{kind: :string, values: ~w(vertical horizontal)}

        "TABLE_SIZE" ->
          # @carbon/web-components/es/components/data-table/defs.d.ts
          %{kind: :string, values: ~w(xs sm md lg xl)}

        "TABLE_SORT_CYCLE" ->
          # @carbon/web-components/es/components/data-table/defs.d.ts
          %{
            kind: :string,
            values:
              ~w(bi-states-from-ascending bi-states-from-descending tri-states-from-ascending tri-states-from-descending)
          }

        "TABLE_SORT_DIRECTION" ->
          # @carbon/web-components/es/components/data-table/defs.d.ts
          %{kind: :string, values: ~w(xs sm md lg xl)}

        "TABS_TYPE" ->
          # @carbon/web-components/es/components/tabs/defs.d.ts
          %{kind: :string, values: ["", "container", "contained"]}

        "TEARSHEET_INFLUENCER_PLACEMENT" ->
          # @carbon/web-components/es/components/tearsheet/defs.d.ts
          %{kind: :string, values: ~w(right left)}

        "TEARSHEET_INFLUENCER_WIDTH" ->
          # @carbon/web-components/es/components/tearsheet/defs.d.ts
          %{kind: :string, values: ~w(narrow wide)}

        "TEARSHEET_WIDTH" ->
          # @carbon/web-components/es/components/tearsheet/defs.d.ts
          %{kind: :string, values: ~w(narrow wide)}

        "TOGGLE_SIZE" ->
          # @carbon/web-components/es/components/toggle/defs.d.ts
          %{kind: :string, values: ["", "sm"]}

        _ ->
          case Graphene.CodeGen.Metadata.type_values() do
            %{^cleanname => values} when is_list(values) and values != [] ->
              %{kind: :string, values: values}

            _ ->
              %{}
          end
      end

    case {undefined?, info} do
      {true, %{values: list}} when is_list(list) ->
        struct(__MODULE__, %{info | values: [nil | list]})

      _ ->
        struct(__MODULE__, info)
    end
  end
end
