defmodule Graphene.Internal.ProductCoreComponents do
  @moduledoc """
  Autogenerated module. Do not edit directly.
  """

  use Phoenix.Component

  def version(), do: ~S|0.33.0|

  @doc """
  Component `<c4p-about-modal>` from `./src/components/about-modal/about-modal.ts`

  About Modal.

  ## Events

  * `c4p-about-modal-beingclosed` - The custom event fired before this about modal is being closed upon a user gesture.
  Cancellation of this event stops the user-initiated action of closing this about modal.
  * `c4p-about-modal-closed` - The custom event fired after this about modal is closed upon a user gesture.

  """

  attr :additional_info, :any,
    default: nil,
    doc:
      "If you are legally required to display logos of technologies used to build your product you can provide this in the additionalInfo. Additional information will be displayed in the footer."

  attr :close_icon_description, :string,
    default: "close",
    doc: "Determines if About Modal is open or not."

  attr :content, :any,
    default: nil,
    doc:
      "Subhead text providing any relevant product disclaimers including legal information (optional)"

  attr :copyright_text, :any, default: nil, doc: "Determines if About Modal is open or not."

  attr :links, :any,
    default: nil,
    doc:
      "An array of Carbon `Link` component if there are additional information to call out within the card. The about modal should be used to display the product information and not where users go to find help (optional)"

  attr :logo, :any, default: nil, doc: "A visual symbol used to represent the product."
  attr :open, :boolean, default: true, doc: "Determines if About Modal is open or not."

  attr :title, :any,
    default: nil,
    doc:
      "Header text that provides the product name. The IBM Services logo consists of two discrete, but required, elements: the iconic IBM 8-bar logo represented alongside the IBM Services logotype. Please follow these guidelines to ensure proper execution."

  attr :version, :any,
    default: nil,
    doc: "Text that provides information on the version number of your product."

  attr :rest, :global

  slot :inner_block

  def about_modal(assigns) do
    ~H"""
    <c4p-about-modal
      additionalInfo={assigns[:additional_info]}
      closeIconDescription={assigns[:close_icon_description]}
      content={assigns[:content]}
      copyrightText={assigns[:copyright_text]}
      links={assigns[:links]}
      logo={assigns[:logo]}
      open={assigns[:open]}
      title={assigns[:title]}
      version={assigns[:version]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-about-modal>
    """
  end

  @doc """
  Component `<c4p-big-number>` from `./src/components/big-number/big-number.ts`

  Undocumented


  """

  attr :fraction_digits, :string, default: "1"
  attr :loading, :boolean, default: false
  attr :locale, :string, default: "en-US"
  attr :percentage, :boolean, default: false
  attr :size, :string, default: "default", values: ["default", "lg", "xl"]
  attr :total, :string, default: nil
  attr :trending, :boolean, default: false
  attr :truncate, :boolean, default: true
  attr :value, :string, default: nil
  attr :rest, :global

  slot :icon_button, doc: "Displays an icon button next to `value`.", do: attr(:tag, :string)

  slot :label,
    doc:
      "Header area that displays the label above the value. This slot can be customized to include an info icon and a tooltip for additional context.",
    do: attr(:tag, :string)

  slot :trending_icon,
    doc:
      "Displays an icon indicating trend direction. Can be customized to show a downward arrow when the trend is not upward.",
    do: attr(:tag, :string)

  slot :inner_block

  def big_number(assigns) do
    ~H"""
    <c4p-big-number
      fraction-digits={assigns[:fraction_digits]}
      loading={assigns[:loading]}
      locale={assigns[:locale]}
      percentage={assigns[:percentage]}
      size={assigns[:size]}
      total={assigns[:total]}
      trending={assigns[:trending]}
      truncate={assigns[:truncate]}
      value={assigns[:value]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag
        :for={s <- assigns[:icon_button]}
        tag_name={Map.get(s, :tag, "div")}
        slot="icon-button"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:label]} tag_name={Map.get(s, :tag, "div")} slot="label">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:trending_icon]}
        tag_name={Map.get(s, :tag, "div")}
        slot="trending-icon"
      >
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-big-number>
    """
  end

  @doc """
  Component `<c4p-big-number-skeleton>` from `./src/components/big-number/big-number-skeleton.ts`

  Undocumented


  """

  attr :size, :string, default: "default", values: [nil, "default", "lg", "xl"]
  attr :rest, :global

  slot :inner_block

  def big_number_skeleton(assigns) do
    ~H"""
    <c4p-big-number-skeleton
      size={assigns[:size]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-big-number-skeleton>
    """
  end

  @doc """
  Component `<c4p-checklist>` from `./src/components/checklist/checklist.ts`

  Undocumented

  ## Events

  * `c4p-checklist-view-all` - The custom event which is fired when a user clicks on View All button in checklist footer.
  * `c4p-checklist-toggle` - The custom event which is fired when user clicks on toggle button in checklist header.

  """

  attr :chart_label, :any, default: nil, doc: "The label for progress indicator chart"

  attr :chart_value, :any,
    default: nil,
    doc: "A number between 0 and 1 which indicates the progress of checklist"

  attr :disable_toggle, :boolean,
    default: false,
    doc: "Whether or not to show the open/close toggle."

  attr :open, :boolean,
    default: false,
    doc: "Specifies whether the component is opened or closed."

  attr :title, :any, default: nil, doc: "The title of the component."

  attr :toggle_aria_label, :any,
    default: nil,
    doc: "Aria-label for the Checklist's toggle component."

  attr :toggle_label, :any, default: nil, doc: "The label for the toggle's tooltip."
  attr :toggle_label_align, :any, default: nil, doc: "The alignment of the toggle's tooltip."

  attr :view_all_label, :any,
    default: nil,
    doc: "If defined, will show and enable the \"View all (#)\" button in the checklist footer."

  attr :rest, :global

  slot :checklist_footer,
    doc: "Optional footer area for actions like buttons, links, or additional notes.",
    do: attr(:tag, :string)

  slot :checklist_header,
    doc: "Header area which includes the title and the progress indicator.",
    do: attr(:tag, :string)

  slot :header_chart,
    doc: "Header chart slot for the checklist progress indicator.",
    do: attr(:tag, :string)

  slot :header_title, doc: "Header title slot for the checklist.", do: attr(:tag, :string)

  slot :header_chart_label,
    doc: "Header chart label slot for the checklist.",
    do: attr(:tag, :string)

  slot :inner_block

  def checklist(assigns) do
    ~H"""
    <c4p-checklist
      chart-label={assigns[:chart_label]}
      chart-value={assigns[:chart_value]}
      disable-toggle={assigns[:disable_toggle]}
      open={assigns[:open]}
      title={assigns[:title]}
      toggle-aria-label={assigns[:toggle_aria_label]}
      toggle-label={assigns[:toggle_label]}
      toggle-label-align={assigns[:toggle_label_align]}
      view-all-label={assigns[:view_all_label]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag
        :for={s <- assigns[:checklist_footer]}
        tag_name={Map.get(s, :tag, "div")}
        slot="checklist-footer"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:checklist_header]}
        tag_name={Map.get(s, :tag, "div")}
        slot="checklist-header"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:header_chart]}
        tag_name={Map.get(s, :tag, "div")}
        slot="header-chart"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:header_title]}
        tag_name={Map.get(s, :tag, "div")}
        slot="header-title"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:header_chart_label]}
        tag_name={Map.get(s, :tag, "div")}
        slot="header-chartLabel"
      >
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-checklist>
    """
  end

  @doc """
  Component `<c4p-checklist-chart>` from `./src/components/checklist/checklist-chart.ts`

  Undocumented


  """

  attr :value, :string,
    default: "0",
    doc: "A number between 0 and 1 which indicates the progress of checklist"

  attr :rest, :global

  slot :inner_block

  def checklist_chart(assigns) do
    ~H"""
    <c4p-checklist-chart
      value={assigns[:value]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-checklist-chart>
    """
  end

  @doc """
  Component `<c4p-checklist-group>` from `./src/components/checklist/checklist-group.ts`

  Sections in c4p-checklist


  """

  attr :title, :any, default: nil, doc: "Title text of the c4p-checklist-group"
  attr :rest, :global

  slot :inner_block

  def checklist_group(assigns) do
    ~H"""
    <c4p-checklist-group
      title={assigns[:title]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-checklist-group>
    """
  end

  @doc """
  Component `<c4p-checklist-icon>` from `./src/components/checklist/checklist-icon.ts`

  Undocumented


  """

  attr :kind, :any,
    default: nil,
    doc:
      "The icon to be displayed.\nValues can be 'unchecked', 'indeterminate', 'checked', 'error', 'disabled'"

  attr :rest, :global

  slot :inner_block

  def checklist_icon(assigns) do
    ~H"""
    <c4p-checklist-icon
      kind={assigns[:kind]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-checklist-icon>
    """
  end

  @doc """
  Component `<c4p-checklist-item>` from `./src/components/checklist/checklist-item.ts`

  item in c4p-checklist-group

  ## Events

  * `c4p-checklist-item-clicked` - The custom event which is fired when a user clicks on checklist item with clickable attribute.

  """

  attr :clickable, :boolean,
    default: false,
    doc: "When true, makes the checklist item label clickable"

  attr :label, :any, default: nil, doc: "label of the c4p-checklist-item"

  attr :status, :any,
    default: nil,
    doc:
      "status of the c4p-checklist-item\nValues can be 'not started', 'in progress', 'completed', 'error', 'disabled'"

  attr :rest, :global

  slot :content, doc: "checklist item title/description", do: attr(:tag, :string)
  slot :icon, doc: "checklist item icon, usually a status indicator icon", do: attr(:tag, :string)
  slot :inner_block

  def checklist_item(assigns) do
    ~H"""
    <c4p-checklist-item
      clickable={assigns[:clickable]}
      label={assigns[:label]}
      status={assigns[:status]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:content]} tag_name={Map.get(s, :tag, "div")} slot="content">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:icon]} tag_name={Map.get(s, :tag, "div")} slot="icon">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-checklist-item>
    """
  end

  @doc """
  Component `<c4p-coachmark>` from `./src/components/coachmark/coachmark.ts`

  coachmark main component

  ## Events

  * `c4p-coachmark-opened` - The custom event fired when the coachmark is opened.
  This event can be used to perform actions such as focusing elements when the coachmark becomes visible.

  """

  attr :align, :string,
    default: "top",
    doc: "Where to render the Coachmark relative to its target."

  attr :drop_shadow, :boolean,
    default: false,
    doc: "Specify whether a drop shadow should be rendered on the popover."

  attr :floating, :boolean,
    default: false,
    doc: "Specifies whether the component is floating or not."

  attr :high_contrast, :boolean,
    default: false,
    doc: "Specify whether the component should be rendered on high-contrast."

  attr :open, :boolean, default: false, doc: "Specifies whether the component is currently open."
  attr :position, :any, default: nil, doc: "Fine tune the position of the target in pixels."
  attr :rest, :global

  slot :trigger, doc: "Trigger element for the coachmark.", do: attr(:tag, :string)
  slot :inner_block

  def coachmark(assigns) do
    ~H"""
    <c4p-coachmark
      align={assigns[:align]}
      dropShadow={assigns[:drop_shadow]}
      floating={assigns[:floating]}
      highContrast={assigns[:high_contrast]}
      open={assigns[:open]}
      position={assigns[:position]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:trigger]} tag_name={Map.get(s, :tag, "div")} slot="trigger">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-coachmark>
    """
  end

  @doc """
  Component `<c4p-coachmark-beacon>` from `./src/components/coachmark/coachmark-beacon/coachmark-beacon.ts`

  CoachmarkBeacon.

  ## Events

  * `c4p-coachmark-beacon-clicked` - Custom event fired when beacon is clicked

  """

  attr :expanded, :boolean, default: false, doc: "specify aria-expanded of beacon"
  attr :id, :string, default: "crypto.randomUUID()", doc: "id for the coachmark beacon"

  attr :kind, :string,
    default: "default",
    values: [nil, "default"],
    doc:
      "What style of beacon.\nBEACON_KIND is an enum from the Coachmark and can be used for this value."

  attr :label, :string, default: "Show information", doc: "The aria label."
  attr :rest, :global

  slot :icon, doc: "Custom icon for the beacon.", do: attr(:tag, :string)
  slot :inner_block

  def coachmark_beacon(assigns) do
    ~H"""
    <c4p-coachmark-beacon
      expanded={assigns[:expanded]}
      id={assigns[:id]}
      kind={assigns[:kind]}
      label={assigns[:label]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:icon]} tag_name={Map.get(s, :tag, "div")} slot="icon">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-coachmark-beacon>
    """
  end

  @doc """
  Component `<c4p-coachmark-body>` from `./src/components/coachmark/coachmark-body.ts`

  coachmark-body for content body


  """

  attr :rest, :global

  slot :inner_block

  def coachmark_body(assigns) do
    ~H"""
    <c4p-coachmark-body {@rest}>
      {render_slot(@inner_block)}
    </c4p-coachmark-body>
    """
  end

  @doc """
  Component `<c4p-coachmark-header>` from `./src/components/coachmark/coachmark-header.ts`

  coachmark-header for content header section


  """

  attr :close_icon_description, :string,
    default: nil,
    doc: "Tooltip text and aria label for the Close button icon."

  attr :drag_icon_description, :string,
    default: nil,
    doc: "Tooltip text and aria label for the Drag button icon."

  attr :rest, :global

  slot :header, doc: "Coachmark header content.", do: attr(:tag, :string)
  slot :inner_block

  def coachmark_header(assigns) do
    ~H"""
    <c4p-coachmark-header
      closeIconDescription={assigns[:close_icon_description]}
      dragIconDescription={assigns[:drag_icon_description]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:header]} tag_name={Map.get(s, :tag, "div")} slot="header">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-coachmark-header>
    """
  end

  @doc """
  Component `<c4p-coachmark-tagline>` from `./src/components/coachmark/coachmark-tagline/coachmark-tagline.ts`

  DO NOT USE. This component is for the exclusive use
  of other Onboarding components.

  Coachmark tagline component.

  ## Events

  * `c4p-coachmark-tagline-close` - Custom event fired when close button is clicked
  * `c4p-coachmark-tagline-cta-click` - Custom event fired when tagline CTA is clicked

  """

  attr :close_icon_description, :string,
    default: "Close",
    doc: "Tooltip text and aria label for the Close button icon."

  attr :open, :boolean, default: false, doc: "Whether the tagline is open."
  attr :title, :string, default: nil, doc: "The title of the tagline."
  attr :rest, :global

  slot :inner_block

  def coachmark_tagline(assigns) do
    ~H"""
    <c4p-coachmark-tagline
      close-icon-description={assigns[:close_icon_description]}
      open={assigns[:open]}
      title={assigns[:title]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-coachmark-tagline>
    """
  end

  @doc """
  Component `<c4p-full-page-error>` from `./src/components/full-page-error/full-page-error.ts`

  FullPageError.


  """

  attr :description, :string, default: nil, doc: "Sets the description text"
  attr :kind, :any, default: nil, doc: "Sets what kind of error it is. '404' | '403' | 'custom'"
  attr :label, :string, default: "Error Label", doc: "Sets the label text"
  attr :title, :string, default: "Title", doc: "Sets the title text"
  attr :rest, :global

  slot :inner_block

  def full_page_error(assigns) do
    ~H"""
    <c4p-full-page-error
      description={assigns[:description]}
      kind={assigns[:kind]}
      label={assigns[:label]}
      title={assigns[:title]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-full-page-error>
    """
  end

  @doc """
  Component `<c4p-guide-banner>` from `./src/components/guide-banner/guide-banner.ts`

  GuideBanner.

  ## Events

  * `c4p-guide-banner-toggle` - Custom event fired when banner is opened
  * `c4p-guide-banner-close` - Custom event fired when banner is closed

  """

  attr :collapse_text, :string, default: nil
  attr :expand_text, :string, default: nil
  attr :open, :boolean, default: false
  attr :title_text, :string, default: nil
  attr :rest, :global

  slot :icon, doc: "Guide banner icon.", do: attr(:tag, :string)
  slot :header, doc: "Guide banner header content.", do: attr(:tag, :string)
  slot :body, doc: "Guide banner body content.", do: attr(:tag, :string)
  slot :footer, doc: "Guide banner footer content.", do: attr(:tag, :string)
  slot :inner_block

  def guide_banner(assigns) do
    ~H"""
    <c4p-guide-banner
      collapseText={assigns[:collapse_text]}
      expandText={assigns[:expand_text]}
      open={assigns[:open]}
      titleText={assigns[:title_text]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:icon]} tag_name={Map.get(s, :tag, "div")} slot="icon">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:header]} tag_name={Map.get(s, :tag, "div")} slot="header">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:body]} tag_name={Map.get(s, :tag, "div")} slot="body">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:footer]} tag_name={Map.get(s, :tag, "div")} slot="footer">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-guide-banner>
    """
  end

  @doc """
  Component `<c4p-guide-banner-element>` from `./src/components/guide-banner/guide-banner-element.ts`

  GuideBannerElement.


  """

  attr :rest, :global

  slot :title, doc: "Guide banner element title.", do: attr(:tag, :string)
  slot :description, doc: "Guide banner element description.", do: attr(:tag, :string)
  slot :inner_block

  def guide_banner_element(assigns) do
    ~H"""
    <c4p-guide-banner-element {@rest}>
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:title]} tag_name={Map.get(s, :tag, "div")} slot="title">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:description]}
        tag_name={Map.get(s, :tag, "div")}
        slot="description"
      >
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-guide-banner-element>
    """
  end

  @doc """
  Component `<c4p-interstitial-screen>` from `./src/components/interstitial-screen/interstitial-screen.ts`

  interstitial-screen main component

  ## Events

  * `c4p-interstitial-opened` - The custom event triggered after loading the component.
  Its event.detail will provide you with carousal api methods for step navigation and method to disable any action button
  *
  * `c4p-interstitial-beingclosed` - The name of the custom event fired before interstitial is being closed upon a user gesture.
  Cancellation of this event stops the user-initiated action of closing the interstitial.
  * `c4p-interstitial-closed` - The name of the custom event fired after this tearsheet is closed upon a user gesture.

  """

  attr :fullscreen, :boolean,
    default: false,
    doc:
      "Specifies whether the component is shown as a full-screen\nexperience, else it is shown as a modal by default."

  attr :open, :boolean, default: false, doc: "Specifies whether the component is currently open."
  attr :rest, :global

  slot :header, doc: "Interstitial screen header content.", do: attr(:tag, :string)
  slot :body, doc: "Interstitial screen body content.", do: attr(:tag, :string)
  slot :footer, doc: "Interstitial screen footer content.", do: attr(:tag, :string)
  slot :inner_block

  def interstitial_screen(assigns) do
    ~H"""
    <c4p-interstitial-screen
      fullscreen={assigns[:fullscreen]}
      open={assigns[:open]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:header]} tag_name={Map.get(s, :tag, "div")} slot="header">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:body]} tag_name={Map.get(s, :tag, "div")} slot="body">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:footer]} tag_name={Map.get(s, :tag, "div")} slot="footer">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-interstitial-screen>
    """
  end

  @doc """
  Component `<c4p-interstitial-screen-body>` from `./src/components/interstitial-screen/interstitial-screen-body.ts`

  interstitial-screen-body for body section

  ## Events

  * `c4p-on-before-step-change` - The name of the custom event fired at the start of  the step change.
  * `c4p-on-after-step-change` - The name of the custom event fired at the end of  the step change.

  """

  attr :slot, :string, default: "body"
  attr :rest, :global

  slot :inner_block

  def interstitial_screen_body(assigns) do
    ~H"""
    <c4p-interstitial-screen-body
      slot={assigns[:slot]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-interstitial-screen-body>
    """
  end

  @doc """
  Component `<c4p-interstitial-screen-body-item>` from `./src/components/interstitial-screen/interstitial-screen-body-item.ts`

  interstitial-screen-body-item for body children


  """

  attr :step_title, :string, default: nil, doc: "This will serve the labels for each step"
  attr :rest, :global

  slot :inner_block

  def interstitial_screen_body_item(assigns) do
    ~H"""
    <c4p-interstitial-screen-body-item
      stepTitle={assigns[:step_title]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-interstitial-screen-body-item>
    """
  end

  @doc """
  Component `<c4p-interstitial-screen-footer>` from `./src/components/interstitial-screen/interstitial-screen-footer.ts`

  interstitial-screen-footer for footer section

  ## Events

  * `c4p-on-action` - The name of the custom event fired just before the action. You can use this event to perform any async/sync validation.
  if you pass async-action = true, the component will wait for an external listener (e.g., a form validation or confirmation modal) to resolve the proceed()
  callback before continuing. When asyncAction is true, you must listen for the eventOnBeforeAction event and call the proceed() function
  (either synchronously or with a promise) to allow navigation.

  """

  attr :async_action, :any,
    default: nil,
    doc:
      "Enables support for asynchronous validation or user confirmation before proceeding\nto the next interstitial step. When set to true, the component will wait for an external\n listener (e.g., a form validation or confirmation modal) to resolve the proceed() callback before continuing.\nWhen asyncAction is true, you must listen for the eventOnBeforeAction event and\ncall the proceed() function (either synchronously or with a promise) to allow navigation."

  attr :next_button_label, :string, default: "Next", doc: "The label for the Next button."
  attr :previous_button_label, :string, default: "Back", doc: "The label for the Previous button."
  attr :skip_button_label, :string, default: "Skip", doc: "The label for the skip button."
  attr :slot, :string, default: "footer"

  attr :start_button_label, :string,
    default: "Get Started",
    doc: "The label for the start button."

  attr :rest, :global

  slot :inner_block

  def interstitial_screen_footer(assigns) do
    ~H"""
    <c4p-interstitial-screen-footer
      async-action={assigns[:async_action]}
      nextButtonLabel={assigns[:next_button_label]}
      previousButtonLabel={assigns[:previous_button_label]}
      skipButtonLabel={assigns[:skip_button_label]}
      slot={assigns[:slot]}
      startButtonLabel={assigns[:start_button_label]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-interstitial-screen-footer>
    """
  end

  @doc """
  Component `<c4p-interstitial-screen-header>` from `./src/components/interstitial-screen/interstitial-screen-header.ts`

  interstitial-screen-header for header section


  """

  attr :close_icon_description, :string,
    default: "Close",
    doc: "Tooltip text and aria label for the Close button icon."

  attr :header_subtitle, :string,
    default: nil,
    doc: "Tooltip text and aria label for the Close button icon."

  attr :header_title, :string,
    default: nil,
    doc: "Provide an optional title to be applied to the header."

  attr :hide_progress_indicator, :boolean,
    default: false,
    doc: "Optional parameter to hide the progress indicator when multiple steps are used."

  attr :slot, :string, default: "header"
  attr :rest, :global

  slot :inner_block

  def interstitial_screen_header(assigns) do
    ~H"""
    <c4p-interstitial-screen-header
      closeIconDescription={assigns[:close_icon_description]}
      header-subtitle={assigns[:header_subtitle]}
      header-title={assigns[:header_title]}
      hideProgressIndicator={assigns[:hide_progress_indicator]}
      slot={assigns[:slot]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-interstitial-screen-header>
    """
  end

  @doc """
  Component `<c4p-notification>` from `./src/components/notification-panel/notification.ts`

  Notification.

  ## Events

  * `c4p-notification-dismiss` - The custom event is fired when the notification is closed by a user gesture.

  """

  attr :timestamp, :any,
    default: nil,
    doc:
      "Sets the timestamp for the notification, typically used to indicate when it was received"

  attr :type, :string,
    default: nil,
    values: [nil, nil, "error", "warning", "success", "informational"],
    doc:
      "Sets the type of notification to display: 'error', 'warning', 'success', or 'informational'"

  attr :rest, :global

  slot :description, doc: "The description for the notification.", do: attr(:tag, :string)
  slot :title, doc: "The Title for the notification.", do: attr(:tag, :string)
  slot :inner_block

  def notification(assigns) do
    ~H"""
    <c4p-notification
      timestamp={assigns[:timestamp]}
      type={assigns[:type]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag
        :for={s <- assigns[:description]}
        tag_name={Map.get(s, :tag, "div")}
        slot="description"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:title]} tag_name={Map.get(s, :tag, "div")} slot="title">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-notification>
    """
  end

  @doc """
  Component `<c4p-notification-footer>` from `./src/components/notification-panel/notification-footer.ts`

  Notification Footer.

  ## Events

  * `c4p-notification-view-all` - The custom event is fired when a user clicks on View All button.
  * `c4p-notification-settings` - The custom event is fired when User clicks on settings button.

  """

  attr :view_all_label, :string, default: "View All", doc: "Label for View All Text"
  attr :rest, :global

  slot :inner_block

  def notification_footer(assigns) do
    ~H"""
    <c4p-notification-footer
      view-all-label={assigns[:view_all_label]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-notification-footer>
    """
  end

  @doc """
  Component `<c4p-notification-panel>` from `./src/components/notification-panel/notification-panel.ts`

  NotificationPanel.

  ## Events

  * `c4p-notification-panel-beingclosed` - The custom event before notification-panel is closed.
  * `c4p-notification-dismiss-all` - The custom event fired after notification-panel is closed upon a user gesture.
  * `c4p-notification-donot-disturb-change` - The custom event fired after notification-panel is closed upon a user gesture.
  * `c4p-notification-click-outside` - The custom event fired after user clicks outside the panel or Esc key is pressed.

  """

  attr :date_time_locale, :string,
    default: nil,
    doc: "The language for each notification's time stamp.\nUsed with `dateTimeStyle`."

  attr :dismiss_all_label, :any,
    default: nil,
    doc: "Sets the label text for the \"Dismiss all\" button in the Notification panel"

  attr :donot_disturb_label, :any,
    default: nil,
    doc: "Sets the label text for the \"Do Not Disturb\" toggle in the Notification panel"

  attr :empty_state_label, :any,
    default: nil,
    doc: "Sets the empty state label text when there are no notifications"

  attr :open, :boolean,
    default: false,
    doc: "Determines whether the notifications panel should render or not"

  attr :previous_text, :any,
    default: nil,
    doc: "Sets the Previous section title for the Notification panel"

  attr :title_text, :any, default: nil, doc: "Sets the Title for the Notification panel"
  attr :today_text, :any, default: nil, doc: "Sets the Today text for the Notification panel"
  attr :trigger_button_ref, :any, default: nil, doc: "Reference to the trigger button"
  attr :rest, :global

  slot :footer, doc: "Footer for the Panel.", do: attr(:tag, :string)
  slot :previous, doc: "Previous Section.", do: attr(:tag, :string)
  slot :today, doc: "Today Section.", do: attr(:tag, :string)
  slot :empty_state, doc: "Empty state content.", do: attr(:tag, :string)
  slot :inner_block

  def notification_panel(assigns) do
    ~H"""
    <c4p-notification-panel
      date-time-locale={assigns[:date_time_locale]}
      dismiss-all-label={assigns[:dismiss_all_label]}
      donot-disturb-label={assigns[:donot_disturb_label]}
      empty-state-label={assigns[:empty_state_label]}
      open={assigns[:open]}
      previous-text={assigns[:previous_text]}
      title-text={assigns[:title_text]}
      today-text={assigns[:today_text]}
      triggerButtonRef={assigns[:trigger_button_ref]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:footer]} tag_name={Map.get(s, :tag, "div")} slot="footer">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:previous]} tag_name={Map.get(s, :tag, "div")} slot="previous">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:today]} tag_name={Map.get(s, :tag, "div")} slot="today">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:empty_state]}
        tag_name={Map.get(s, :tag, "div")}
        slot="empty-state"
      >
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-notification-panel>
    """
  end

  @doc """
  Component `<c4p-options-tile>` from `./src/components/options-tile/options-tile.ts`

  OptionsTile.

  ## Events

  * `c4p-options-tile-open` - Custom event fired when tile is opened
  * `c4p-options-tile-close` - Custom event fired when tile is closed

  """

  attr :default_open, :boolean, default: false, doc: "Determines if the tile is open by default"

  attr :size, :string,
    default: "lg",
    values: [nil, "lg", "xl"],
    doc: "Determines the size of the header"

  attr :title_id, :string, default: nil, doc: "ID for the title"
  attr :title_text, :string, default: nil, doc: "Text for the title"
  attr :rest, :global

  slot :summary, doc: "Summary content for the options tile.", do: attr(:tag, :string)
  slot :body, doc: "Body content for the options tile.", do: attr(:tag, :string)
  slot :toggle, doc: "Toggle action content for the options tile.", do: attr(:tag, :string)
  slot :inner_block

  def options_tile(assigns) do
    ~H"""
    <c4p-options-tile
      defaultOpen={assigns[:default_open]}
      size={assigns[:size]}
      titleId={assigns[:title_id]}
      titleText={assigns[:title_text]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:summary]} tag_name={Map.get(s, :tag, "div")} slot="summary">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:body]} tag_name={Map.get(s, :tag, "div")} slot="body">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:toggle]} tag_name={Map.get(s, :tag, "div")} slot="toggle">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-options-tile>
    """
  end

  @doc """
  Component `<c4p-page-header>` from `./src/components/page-header/page-header.ts`

  Page header.


  """

  attr :rest, :global

  slot :inner_block

  def page_header(assigns) do
    ~H"""
    <c4p-page-header {@rest}>
      {render_slot(@inner_block)}
    </c4p-page-header>
    """
  end

  @doc """
  Component `<c4p-page-header-breadcrumb>` from `./src/components/page-header/page-header-breadcrumb.ts`

  Page header Breadcrumb Bar.


  """

  attr :border, :boolean, default: true, doc: "Specify if breadcrumb bar has bottom border."

  attr :content_actions_flush, :boolean,
    default: false,
    doc: "Set to `true` if content actions should be flush (no padding)"

  attr :page_actions_flush, :boolean,
    default: false,
    doc: "Set to `true` if page actions should be flush (no padding)"

  attr :within_grid, :boolean,
    default: false,
    doc:
      "Set to `true` if the breadcrumb bar is sitting within a grid\n(ie. when used in tandem with page-header-hero-image)"

  attr :rest, :global

  slot :icon, doc: "Breadcrumb icon slot.", do: attr(:tag, :string)
  slot :content_actions, doc: "Content actions slot.", do: attr(:tag, :string)
  slot :page_actions, doc: "Page actions slot.", do: attr(:tag, :string)
  slot :inner_block

  def page_header_breadcrumb(assigns) do
    ~H"""
    <c4p-page-header-breadcrumb
      border={assigns[:border]}
      content-actions-flush={assigns[:content_actions_flush]}
      page-actions-flush={assigns[:page_actions_flush]}
      within-grid={assigns[:within_grid]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:icon]} tag_name={Map.get(s, :tag, "div")} slot="icon">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:content_actions]}
        tag_name={Map.get(s, :tag, "div")}
        slot="content-actions"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:page_actions]}
        tag_name={Map.get(s, :tag, "div")}
        slot="page-actions"
      >
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-page-header-breadcrumb>
    """
  end

  @doc """
  Component `<c4p-page-header-content>` from `./src/components/page-header/page-header-content.ts`

  Page header content.


  """

  attr :title, :string, default: nil, doc: "Title text of the page-header-content"

  attr :within_grid, :boolean,
    default: false,
    doc:
      "Set to `true` if the breadcrumb bar is sitting within a grid\n(ie. when used in tandem with page-header-hero-image)"

  attr :rest, :global

  slot :icon, doc: "Content icon slot.", do: attr(:tag, :string)
  slot :contextual_actions, doc: "Contextual actions slot.", do: attr(:tag, :string)
  slot :page_actions, doc: "Page actions slot.", do: attr(:tag, :string)
  slot :inner_block

  def page_header_content(assigns) do
    ~H"""
    <c4p-page-header-content
      title={assigns[:title]}
      within-grid={assigns[:within_grid]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:icon]} tag_name={Map.get(s, :tag, "div")} slot="icon">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:contextual_actions]}
        tag_name={Map.get(s, :tag, "div")}
        slot="contextual-actions"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:page_actions]}
        tag_name={Map.get(s, :tag, "div")}
        slot="page-actions"
      >
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-page-header-content>
    """
  end

  @doc """
  Component `<c4p-page-header-content-text>` from `./src/components/page-header/page-header-content-text.ts`

  Page header Content Text.


  """

  attr :subtitle, :string, default: nil, doc: "Subtitle text of the page-header-content"
  attr :rest, :global

  slot :inner_block

  def page_header_content_text(assigns) do
    ~H"""
    <c4p-page-header-content-text
      subtitle={assigns[:subtitle]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-page-header-content-text>
    """
  end

  @doc """
  Component `<c4p-page-header-hero-image>` from `./src/components/page-header/page-header-hero-image.ts`

  Page header Hero Image.


  """

  attr :rest, :global

  slot :inner_block

  def page_header_hero_image(assigns) do
    ~H"""
    <c4p-page-header-hero-image {@rest}>
      {render_slot(@inner_block)}
    </c4p-page-header-hero-image>
    """
  end

  @doc """
  Component `<c4p-page-header-scroller>` from `./src/components/page-header/page-header-scroller.ts`

  Page header Scroller button


  """

  attr :align, :string,
    default: "top",
    doc: "Specify how the trigger should align with the tooltip"

  attr :autoalign, :boolean,
    default: true,
    doc: "Specify whether a auto align functionality should be applied"

  attr :close_on_activation, :boolean,
    default: true,
    doc:
      "Determines whether the tooltip should close when inner content is activated (click, Enter or Space)"

  attr :collapse_text, :string,
    default: "Collapse",
    doc: "Specify the collapse text for the scroller button"

  attr :default_open, :boolean,
    default: false,
    doc: "Specify whether the tooltip should be open when it first renders"

  attr :enter_delay_ms, :string,
    default: "100",
    doc: "Specify the duration in milliseconds to delay before displaying the tooltip"

  attr :expand_text, :string,
    default: "Expand",
    doc: "Specify the expand text for the scroller button"

  attr :leave_delay_ms, :string,
    default: "300",
    doc: "Specify the duration in milliseconds to delay before hiding the tooltip"

  attr :size, :string, default: "md", doc: "Specify the size of the Button. Defaults to `md`."
  attr :rest, :global

  slot :tooltip_content, doc: "Tooltip content slot.", do: attr(:tag, :string)
  slot :inner_block

  def page_header_scroller(assigns) do
    ~H"""
    <c4p-page-header-scroller
      align={assigns[:align]}
      autoalign={assigns[:autoalign]}
      close-on-activation={assigns[:close_on_activation]}
      collapseText={assigns[:collapse_text]}
      defaultOpen={assigns[:default_open]}
      enter-delay-ms={assigns[:enter_delay_ms]}
      expandText={assigns[:expand_text]}
      leave-delay-ms={assigns[:leave_delay_ms]}
      size={assigns[:size]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag
        :for={s <- assigns[:tooltip_content]}
        tag_name={Map.get(s, :tag, "div")}
        slot="tooltip-content"
      >
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-page-header-scroller>
    """
  end

  @doc """
  Component `<c4p-page-header-tabs>` from `./src/components/page-header/page-header-tabs.ts`

  Page header Tabs Bar.


  """

  attr :rest, :global

  slot :tags, doc: "Tags slot for the tab bar.", do: attr(:tag, :string)
  slot :scroller, doc: "Scroller slot for the tab bar.", do: attr(:tag, :string)
  slot :inner_block

  def page_header_tabs(assigns) do
    ~H"""
    <c4p-page-header-tabs {@rest}>
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:tags]} tag_name={Map.get(s, :tag, "div")} slot="tags">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:scroller]} tag_name={Map.get(s, :tag, "div")} slot="scroller">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-page-header-tabs>
    """
  end

  @doc """
  Component `<c4p-page-header-title-breadcrumb>` from `./src/components/page-header/page-header-title-breadcrumb.ts`

  Page header Title Breadcrumb


  """

  attr :rest, :global

  slot :inner_block

  def page_header_title_breadcrumb(assigns) do
    ~H"""
    <c4p-page-header-title-breadcrumb {@rest}>
      {render_slot(@inner_block)}
    </c4p-page-header-title-breadcrumb>
    """
  end

  @doc """
  Component `<c4p-side-panel>` from `./src/components/side-panel/side-panel.ts`

  SidePanel.

  ## Events

  * `c4p-side-panel-beingclosed` - The custom event fired before this side-panel is being closed upon a user gesture.
  Cancellation of this event stops the user-initiated action of closing this side-panel.
  * `c4p-side-panel-closed` - The custom event fired after this side-panel is closed upon a user gesture.
  * `c4p-side-panel-navigate-back` - custom event fired when clicking navigate back (available when step > 0)

  """

  attr :animate_title, :boolean,
    default: true,
    doc: "Determines if the title will animate on scroll"

  attr :close_icon_description, :string,
    default: "Close",
    doc: "Sets the close button icon description"

  attr :close_icon_tooltip_alignment, :string,
    default: "left",
    doc: "Sets the close button tooltip alignment"

  attr :condensed_actions, :boolean,
    default: false,
    doc:
      "Determines whether the side panel should render the condensed version (affects action buttons primarily)"

  attr :current_step, :any, default: nil, doc: "Sets the current step of the side panel"
  attr :hide_close_button, :boolean, default: false, doc: "Show/hide the \"X\" close button"

  attr :include_overlay, :boolean,
    default: false,
    doc: "Determines whether the side panel should render with an overlay"

  attr :label_text, :any,
    default: nil,
    doc: "Sets the label text which will display above the title text"

  attr :navigation_back_icon_description, :string,
    default: "Back",
    doc: "Sets the icon description for the navigation back icon button"

  attr :open, :boolean, default: false, doc: "`true` if the side-panel should be open."

  attr :placement, :string,
    default: "right",
    values: ["right", "left"],
    doc: "SidePanel placement."

  attr :prevent_close_on_click_outside, :boolean,
    default: false,
    doc: "Prevent closing on click outside of side-panel"

  attr :selector_initial_focus, :any,
    default: nil,
    doc: "The initial location of focus in the side panel"

  attr :selector_page_content, :string,
    default: nil,
    doc: "Selector for page content, used to push content to side except"

  attr :size, :string,
    default: "md",
    values: ["xs", "sm", "md", "lg", "2xl"],
    doc: "SidePanel size."

  attr :slide_in, :boolean, default: false, doc: "Determines if this panel slides in"
  attr :title, :any, default: nil, doc: "Sets the title text"
  attr :rest, :global

  slot :above_title, doc: "Content above the title.", do: attr(:tag, :string)
  slot :below_title, doc: "Content below the title.", do: attr(:tag, :string)
  slot :slug, doc: "Slug slot for the side panel header.", do: attr(:tag, :string)
  slot :subtitle, doc: "Subtitle slot for the side panel header.", do: attr(:tag, :string)
  slot :action_toolbar, doc: "Action toolbar slot.", do: attr(:tag, :string)
  slot :actions, doc: "Footer actions slot.", do: attr(:tag, :string)
  slot :inner_block

  def side_panel(assigns) do
    ~H"""
    <c4p-side-panel
      animate-title={assigns[:animate_title]}
      close-icon-description={assigns[:close_icon_description]}
      close-icon-tooltip-alignment={assigns[:close_icon_tooltip_alignment]}
      condensed-actions={assigns[:condensed_actions]}
      current-step={assigns[:current_step]}
      hide-close-button={assigns[:hide_close_button]}
      include-overlay={assigns[:include_overlay]}
      label-text={assigns[:label_text]}
      navigation-back-icon-description={assigns[:navigation_back_icon_description]}
      open={assigns[:open]}
      placement={assigns[:placement]}
      prevent-close-on-click-outside={assigns[:prevent_close_on_click_outside]}
      selector-initial-focus={assigns[:selector_initial_focus]}
      selector-page-content={assigns[:selector_page_content]}
      size={assigns[:size]}
      slide-in={assigns[:slide_in]}
      title={assigns[:title]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag
        :for={s <- assigns[:above_title]}
        tag_name={Map.get(s, :tag, "div")}
        slot="above-title"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:below_title]}
        tag_name={Map.get(s, :tag, "div")}
        slot="below-title"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:slug]} tag_name={Map.get(s, :tag, "div")} slot="slug">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:subtitle]} tag_name={Map.get(s, :tag, "div")} slot="subtitle">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:action_toolbar]}
        tag_name={Map.get(s, :tag, "div")}
        slot="action-toolbar"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:actions]} tag_name={Map.get(s, :tag, "div")} slot="actions">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-side-panel>
    """
  end

  @doc """
  Component `<c4p-tearsheet>` from `./src/components/tearsheet/tearsheet.ts`

  Tearsheet.

  ## Events

  * `c4p-tearsheet-beingclosed` - The custom event fired before this tearsheet is being closed upon a user gesture.
  Cancellation of this event stops the user-initiated action of closing this tearsheet.
  * `c4p-tearsheet-closed` - The custom event fired after this tearsheet is closed upon a user gesture.

  """

  attr :close_icon_description, :string,
    default: "Close",
    doc: "Sets the close button icon description"

  attr :has_close_icon, :boolean,
    default: false,
    doc:
      "Enable a close icon ('x') in the header area of the tearsheet. By default,\n(when this prop is omitted, or undefined or null) a tearsheet does not\ndisplay a close icon if there are navigation actions (\"transactional\ntearsheet\") and displays one if there are no navigation actions (\"passive\ntearsheet\"), and that behavior can be overridden if required by setting\nthis prop to either true or false."

  attr :influencer_placement, :string,
    default: "right",
    values: ["right", "left"],
    doc: "The placement of the influencer section, 'left' or 'right'."

  attr :influencer_width, :string,
    default: "narrow",
    values: ["narrow", "wide"],
    doc: "The width of the influencer section, 'narrow' or 'wide'."

  attr :open, :boolean, default: false, doc: "`true` if the tearsheet should be open."

  attr :prevent_close_on_click_outside, :boolean,
    default: false,
    doc: "Prevent closing on click outside of tearsheet"

  attr :selector_initial_focus, :any,
    default: nil,
    doc: "The initial location of focus in the side panel"

  attr :width, :string,
    default: "narrow",
    values: ["narrow", "wide"],
    doc: "The width of the influencer section, 'narrow' or 'wide'."

  attr :rest, :global

  slot :label, doc: "Tearsheet label slot.", do: attr(:tag, :string)
  slot :title, doc: "Tearsheet title slot.", do: attr(:tag, :string)
  slot :description, doc: "Tearsheet description slot.", do: attr(:tag, :string)
  slot :header_actions, doc: "Header action buttons slot.", do: attr(:tag, :string)
  slot :header_navigation, doc: "Header navigation slot.", do: attr(:tag, :string)
  slot :decorator, doc: "Decorator slot.", do: attr(:tag, :string)
  slot :slug, doc: "Slug slot.", do: attr(:tag, :string)
  slot :influencer, doc: "Influencer content slot.", do: attr(:tag, :string)
  slot :actions, doc: "Footer actions slot.", do: attr(:tag, :string)
  slot :inner_block

  def tearsheet(assigns) do
    ~H"""
    <c4p-tearsheet
      close-icon-description={assigns[:close_icon_description]}
      has-close-icon={assigns[:has_close_icon]}
      influencer-placement={assigns[:influencer_placement]}
      influencer-width={assigns[:influencer_width]}
      open={assigns[:open]}
      prevent-close-on-click-outside={assigns[:prevent_close_on_click_outside]}
      selector-initial-focus={assigns[:selector_initial_focus]}
      width={assigns[:width]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag :for={s <- assigns[:label]} tag_name={Map.get(s, :tag, "div")} slot="label">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:title]} tag_name={Map.get(s, :tag, "div")} slot="title">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:description]}
        tag_name={Map.get(s, :tag, "div")}
        slot="description"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:header_actions]}
        tag_name={Map.get(s, :tag, "div")}
        slot="header-actions"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:header_navigation]}
        tag_name={Map.get(s, :tag, "div")}
        slot="header-navigation"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:decorator]}
        tag_name={Map.get(s, :tag, "div")}
        slot="decorator"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:slug]} tag_name={Map.get(s, :tag, "div")} slot="slug">
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag
        :for={s <- assigns[:influencer]}
        tag_name={Map.get(s, :tag, "div")}
        slot="influencer"
      >
        {render_slot(s)}
      </.dynamic_tag>
      <.dynamic_tag :for={s <- assigns[:actions]} tag_name={Map.get(s, :tag, "div")} slot="actions">
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-tearsheet>
    """
  end

  @doc """
  Component `<c4p-truncated-text>` from `./src/components/truncated-text/truncated-text.ts`

  TruncatedText.


  """

  attr :align, :string,
    default: "top",
    doc: "Specify how the tooltip should align with the content."

  attr :autoalign, :boolean,
    default: false,
    doc: "Specify whether a auto align functionality should be applied"

  attr :collapse_label, :string, default: nil, doc: "The label on the collapse button."
  attr :expand_label, :string, default: nil, doc: "The label on expand button."
  attr :id, :string, default: nil, doc: "Unique identifier for the element."

  attr :lines, :string,
    default: "0",
    doc: "The maximum number of lines to display before truncation."

  attr :type, :string,
    default: "tooltip",
    values: ["tooltip", "expand"],
    doc:
      "The method to display the full text when truncated. Options are \"tooltip\" or \"expand\". if not passed, the text would just be truncated with ellipsis."

  attr :value, :string, default: nil, doc: "The string value to be truncated."
  attr :rest, :global

  slot :inner_block

  def truncated_text(assigns) do
    ~H"""
    <c4p-truncated-text
      align={assigns[:align]}
      autoalign={assigns[:autoalign]}
      collapse-label={assigns[:collapse_label]}
      expand-label={assigns[:expand_label]}
      id={assigns[:id]}
      lines={assigns[:lines]}
      type={assigns[:type]}
      value={assigns[:value]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </c4p-truncated-text>
    """
  end

  @doc """
  Component `<c4p-user-avatar>` from `./src/components/user-avatar/user-avatar.ts`

  Useravatar.


  """

  attr :background_color, :string,
    default: "order-1-cyan",
    doc: "Provide the background color need to be set for UserAvatar."

  attr :image, :any,
    default: nil,
    doc: "When passing the image prop, supply a full path to the image to be displayed."

  attr :image_description, :any,
    default: nil,
    doc:
      "When passing the image prop use the imageDescription prop to describe the image for screen reader."

  attr :name, :any,
    default: nil,
    doc:
      "When passing the name prop, either send the initials to be used or the user's full name. The first two capital letters of the user's name will be used as the name."

  attr :size, :any, default: nil, doc: "Set the size of the avatar circle"
  attr :theme, :any, default: nil, doc: "Set theme in which the component will be rendered."

  attr :tooltip_alignment, :string,
    default: "bottom",
    doc: "Specify the alignment of the tooltip."

  attr :tooltip_text, :any, default: nil, doc: "Specify the text of the tooltip.\nCan be string"
  attr :rest, :global

  slot :rendericon, doc: "Custom icon slot for the avatar.", do: attr(:tag, :string)
  slot :inner_block

  def user_avatar(assigns) do
    ~H"""
    <c4p-user-avatar
      background-color={assigns[:background_color]}
      image={assigns[:image]}
      image-description={assigns[:image_description]}
      name={assigns[:name]}
      size={assigns[:size]}
      theme={assigns[:theme]}
      tooltip-alignment={assigns[:tooltip_alignment]}
      tooltip-text={assigns[:tooltip_text]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <.dynamic_tag
        :for={s <- assigns[:rendericon]}
        tag_name={Map.get(s, :tag, "div")}
        slot="rendericon"
      >
        {render_slot(s)}
      </.dynamic_tag>
    </c4p-user-avatar>
    """
  end

  defp merge_rest_class(assigns, class_name) do
    rest = Map.get(assigns, :rest, %{})
    class_value = merge_class_value(Map.get(rest, :class), class_name)
    rest = Map.put(rest, :class, class_value)
    assign(assigns, :rest, rest)
  end

  defp merge_rest_class_if(assigns, condition, class_name) do
    if condition, do: merge_rest_class(assigns, class_name), else: assigns
  end

  defp merge_class_value(nil, class_name), do: class_name
  defp merge_class_value("", class_name), do: class_name

  defp merge_class_value(class_value, class_name) when is_list(class_value) do
    class_value
    |> Enum.map(&to_string/1)
    |> Enum.join(" ")
    |> merge_class_value(class_name)
  end

  defp merge_class_value(class_value, class_name) when is_binary(class_value) do
    if String.contains?(class_value, class_name) do
      class_value
    else
      class_value <> " " <> class_name
    end
  end

  defp merge_class_value(_class_value, class_name), do: class_name

  def available_components() do
    [
      "about_modal",
      "big_number",
      "big_number_skeleton",
      "checklist",
      "checklist_chart",
      "checklist_group",
      "checklist_icon",
      "checklist_item",
      "coachmark",
      "coachmark_beacon",
      "coachmark_body",
      "coachmark_header",
      "coachmark_tagline",
      "full_page_error",
      "guide_banner",
      "guide_banner_element",
      "interstitial_screen",
      "interstitial_screen_body",
      "interstitial_screen_body_item",
      "interstitial_screen_footer",
      "interstitial_screen_header",
      "notification",
      "notification_footer",
      "notification_panel",
      "options_tile",
      "page_header",
      "page_header_breadcrumb",
      "page_header_content",
      "page_header_content_text",
      "page_header_hero_image",
      "page_header_scroller",
      "page_header_tabs",
      "page_header_title_breadcrumb",
      "side_panel",
      "tearsheet",
      "truncated_text",
      "user_avatar"
    ]
  end
end
