defmodule Graphene.CarbonComponents do
  @moduledoc """
  Graphene.CarbonComponents is autogenerated from Carbon web components metadata.

  High-level Carbon components built on top of internal low-level components.

  These wrappers avoid direct use of <cds-*> tags and expose a single
  namespace for Carbon web components. Component implementations live in
  grouped modules under Graphene.CarbonComponents.* and this module
  delegates to them.
  """

  use Phoenix.Component

  alias Graphene.CarbonComponents.DataTableComponent
  alias Graphene.Internal.FormComponents

  defmacro __using__(_opts) do
    quote do
      import Graphene.CarbonComponents, only: [data_table: 1, file_uploader: 1, ui_shell: 1]
      import Graphene.CarbonComponents.Accordion
      import Graphene.CarbonComponents.ActionableNotification
      import Graphene.CarbonComponents.AiLabel
      import Graphene.CarbonComponents.AiSkeleton
      import Graphene.CarbonComponents.BadgeIndicator
      import Graphene.CarbonComponents.Breadcrumb
      import Graphene.CarbonComponents.Button
      import Graphene.CarbonComponents.ButtonSet
      import Graphene.CarbonComponents.CalloutNotification
      import Graphene.CarbonComponents.ChatButton
      import Graphene.CarbonComponents.Checkbox
      import Graphene.CarbonComponents.ClickableTile
      import Graphene.CarbonComponents.CodeSnippet
      import Graphene.CarbonComponents.Column
      import Graphene.CarbonComponents.Combo
      import Graphene.CarbonComponents.ComboBox
      import Graphene.CarbonComponents.ContainedList
      import Graphene.CarbonComponents.ContentSwitcher
      import Graphene.CarbonComponents.Copy
      import Graphene.CarbonComponents.DatePicker
      import Graphene.CarbonComponents.DatePickerInput
      import Graphene.CarbonComponents.DefinitionTooltip
      import Graphene.CarbonComponents.DismissibleTag
      import Graphene.CarbonComponents.Dropdown
      import Graphene.CarbonComponents.ExpandableTile
      import Graphene.CarbonComponents.FeatureFlags
      import Graphene.CarbonComponents.FileUploader
      import Graphene.CarbonComponents.FluidNumberInput
      import Graphene.CarbonComponents.FluidSearch
      import Graphene.CarbonComponents.FluidSelect
      import Graphene.CarbonComponents.FluidTextInput
      import Graphene.CarbonComponents.FluidTextarea
      import Graphene.CarbonComponents.Form
      import Graphene.CarbonComponents.Grid
      import Graphene.CarbonComponents.Header
      import Graphene.CarbonComponents.HeaderMenu
      import Graphene.CarbonComponents.HeaderNav
      import Graphene.CarbonComponents.Heading
      import Graphene.CarbonComponents.Icon
      import Graphene.CarbonComponents.Inline
      import Graphene.CarbonComponents.Layer
      import Graphene.CarbonComponents.Link
      import Graphene.CarbonComponents.ListItem
      import Graphene.CarbonComponents.Loading
      import Graphene.CarbonComponents.Menu
      import Graphene.CarbonComponents.MenuItem
      import Graphene.CarbonComponents.Modal
      import Graphene.CarbonComponents.ModalBody
      import Graphene.CarbonComponents.ModalFooter
      import Graphene.CarbonComponents.MultiSelect
      import Graphene.CarbonComponents.NumberInput
      import Graphene.CarbonComponents.OperationalTag
      import Graphene.CarbonComponents.OrderedList
      import Graphene.CarbonComponents.OverflowMenu
      import Graphene.CarbonComponents.PageHeader
      import Graphene.CarbonComponents.PageHeaderContent
      import Graphene.CarbonComponents.Pagination
      import Graphene.CarbonComponents.PasswordInput
      import Graphene.CarbonComponents.Popover
      import Graphene.CarbonComponents.Progress
      import Graphene.CarbonComponents.ProgressIndicator
      import Graphene.CarbonComponents.ProgressStep
      import Graphene.CarbonComponents.Radio
      import Graphene.CarbonComponents.RadioButton
      import Graphene.CarbonComponents.Search
      import Graphene.CarbonComponents.Select
      import Graphene.CarbonComponents.SelectItem
      import Graphene.CarbonComponents.Selectable
      import Graphene.CarbonComponents.ShapeIndicator
      import Graphene.CarbonComponents.Side
      import Graphene.CarbonComponents.SideNav
      import Graphene.CarbonComponents.SideNavMenu
      import Graphene.CarbonComponents.Skeleton
      import Graphene.CarbonComponents.SkipToContent
      import Graphene.CarbonComponents.Slider
      import Graphene.CarbonComponents.Slug
      import Graphene.CarbonComponents.Stack
      import Graphene.CarbonComponents.StructuredList
      import Graphene.CarbonComponents.StructuredListHeader
      import Graphene.CarbonComponents.StructuredListHeaderCell
      import Graphene.CarbonComponents.Switcher
      import Graphene.CarbonComponents.Tab
      import Graphene.CarbonComponents.Table
      import Graphene.CarbonComponents.TableCell
      import Graphene.CarbonComponents.TableHeader
      import Graphene.CarbonComponents.TableToolbar
      import Graphene.CarbonComponents.Tabs
      import Graphene.CarbonComponents.Tag
      import Graphene.CarbonComponents.Tearsheet
      import Graphene.CarbonComponents.TextInput
      import Graphene.CarbonComponents.Textarea
      import Graphene.CarbonComponents.Tile
      import Graphene.CarbonComponents.TimePicker
      import Graphene.CarbonComponents.ToastNotification
      import Graphene.CarbonComponents.Toggle
      import Graphene.CarbonComponents.Toggletip
      import Graphene.CarbonComponents.Tooltip
      import Graphene.CarbonComponents.Tree
      import Graphene.CarbonComponents.UnorderedList
    end
  end

  @doc false
  defdelegate accordion(assigns), to: Graphene.CarbonComponents.Accordion

  @doc false
  defdelegate accordion_item(assigns), to: Graphene.CarbonComponents.Accordion

  @doc false
  defdelegate accordion_skeleton(assigns), to: Graphene.CarbonComponents.Accordion

  @doc false
  defdelegate actionable_notification(assigns),
    to: Graphene.CarbonComponents.ActionableNotification

  @doc false
  defdelegate actionable_notification_button(assigns),
    to: Graphene.CarbonComponents.ActionableNotification

  @doc false
  defdelegate ai_label(assigns), to: Graphene.CarbonComponents.AiLabel

  @doc false
  defdelegate ai_label_action_button(assigns), to: Graphene.CarbonComponents.AiLabel

  @doc false
  defdelegate ai_skeleton_icon(assigns), to: Graphene.CarbonComponents.AiSkeleton

  @doc false
  defdelegate ai_skeleton_placeholder(assigns), to: Graphene.CarbonComponents.AiSkeleton

  @doc false
  defdelegate ai_skeleton_text(assigns), to: Graphene.CarbonComponents.AiSkeleton

  @doc false
  defdelegate badge_indicator(assigns), to: Graphene.CarbonComponents.BadgeIndicator

  @doc false
  defdelegate breadcrumb(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate breadcrumb_item(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate breadcrumb_link(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate breadcrumb_overflow_menu(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate breadcrumb_skeleton(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate button(assigns), to: Graphene.CarbonComponents.Button

  @doc false
  defdelegate button_set(assigns), to: Graphene.CarbonComponents.ButtonSet

  @doc false
  defdelegate button_set_base(assigns), to: Graphene.CarbonComponents.ButtonSet

  @doc false
  defdelegate button_skeleton(assigns), to: Graphene.CarbonComponents.Button

  @doc false
  defdelegate callout_notification(assigns), to: Graphene.CarbonComponents.CalloutNotification

  @doc false
  defdelegate chat_button(assigns), to: Graphene.CarbonComponents.ChatButton

  @doc false
  defdelegate chat_button_skeleton(assigns), to: Graphene.CarbonComponents.ChatButton

  @doc false
  defdelegate checkbox(assigns), to: Graphene.CarbonComponents.Checkbox

  @doc false
  defdelegate checkbox_group(assigns), to: Graphene.CarbonComponents.Checkbox

  @doc false
  defdelegate checkbox_skeleton(assigns), to: Graphene.CarbonComponents.Checkbox

  @doc false
  defdelegate clickable_tile(assigns), to: Graphene.CarbonComponents.ClickableTile

  @doc false
  defdelegate code_snippet(assigns), to: Graphene.CarbonComponents.CodeSnippet

  @doc false
  defdelegate code_snippet_skeleton(assigns), to: Graphene.CarbonComponents.CodeSnippet

  @doc false
  defdelegate column(assigns), to: Graphene.CarbonComponents.Column

  @doc false
  defdelegate column_hang(assigns), to: Graphene.CarbonComponents.Column

  @doc false
  defdelegate combo_box(assigns), to: Graphene.CarbonComponents.ComboBox

  @doc false
  defdelegate combo_box_item(assigns), to: Graphene.CarbonComponents.ComboBox

  @doc false
  defdelegate combo_button(assigns), to: Graphene.CarbonComponents.Combo

  @doc false
  defdelegate contained_list(assigns), to: Graphene.CarbonComponents.ContainedList

  @doc false
  defdelegate contained_list_description(assigns), to: Graphene.CarbonComponents.ContainedList

  @doc false
  defdelegate contained_list_item(assigns), to: Graphene.CarbonComponents.ContainedList

  @doc false
  defdelegate content_switcher(assigns), to: Graphene.CarbonComponents.ContentSwitcher

  @doc false
  defdelegate content_switcher_item(assigns), to: Graphene.CarbonComponents.ContentSwitcher

  @doc false
  defdelegate copy(assigns), to: Graphene.CarbonComponents.Copy

  @doc false
  defdelegate copy_button(assigns), to: Graphene.CarbonComponents.Copy

  @doc false
  defdelegate date_picker(assigns), to: Graphene.CarbonComponents.DatePicker

  @doc false
  defdelegate date_picker_input(assigns), to: Graphene.CarbonComponents.DatePickerInput

  @doc false
  defdelegate date_picker_input_skeleton(assigns), to: Graphene.CarbonComponents.DatePickerInput

  @doc false
  defdelegate definition_tooltip(assigns), to: Graphene.CarbonComponents.DefinitionTooltip

  @doc false
  defdelegate dismissible_tag(assigns), to: Graphene.CarbonComponents.DismissibleTag

  @doc false
  defdelegate dropdown(assigns), to: Graphene.CarbonComponents.Dropdown

  @doc false
  defdelegate dropdown_item(assigns), to: Graphene.CarbonComponents.Dropdown

  @doc false
  defdelegate dropdown_skeleton(assigns), to: Graphene.CarbonComponents.Dropdown

  @doc false
  defdelegate expandable_tile(assigns), to: Graphene.CarbonComponents.ExpandableTile

  @doc false
  defdelegate feature_flags(assigns), to: Graphene.CarbonComponents.FeatureFlags

  @doc false
  defdelegate file_uploader_button(assigns), to: Graphene.CarbonComponents.FileUploader

  @doc false
  defdelegate file_uploader_drop_container(assigns), to: Graphene.CarbonComponents.FileUploader

  @doc false
  defdelegate file_uploader_item(assigns), to: Graphene.CarbonComponents.FileUploader

  @doc false
  defdelegate file_uploader_skeleton(assigns), to: Graphene.CarbonComponents.FileUploader

  @doc false
  defdelegate fluid_number_input(assigns), to: Graphene.CarbonComponents.FluidNumberInput

  @doc false
  defdelegate fluid_number_input_skeleton(assigns), to: Graphene.CarbonComponents.FluidNumberInput

  @doc false
  defdelegate fluid_search(assigns), to: Graphene.CarbonComponents.FluidSearch

  @doc false
  defdelegate fluid_search_skeleton(assigns), to: Graphene.CarbonComponents.FluidSearch

  @doc false
  defdelegate fluid_select(assigns), to: Graphene.CarbonComponents.FluidSelect

  @doc false
  defdelegate fluid_select_skeleton(assigns), to: Graphene.CarbonComponents.FluidSelect

  @doc false
  defdelegate fluid_text_input(assigns), to: Graphene.CarbonComponents.FluidTextInput

  @doc false
  defdelegate fluid_text_input_skeleton(assigns), to: Graphene.CarbonComponents.FluidTextInput

  @doc false
  defdelegate fluid_textarea(assigns), to: Graphene.CarbonComponents.FluidTextarea

  @doc false
  defdelegate fluid_textarea_skeleton(assigns), to: Graphene.CarbonComponents.FluidTextarea

  @doc false
  defdelegate form(assigns), to: Graphene.CarbonComponents.Form

  @doc false
  defdelegate form_group(assigns), to: Graphene.CarbonComponents.Form

  @doc false
  defdelegate form_item(assigns), to: Graphene.CarbonComponents.Form

  @doc false
  defdelegate grid(assigns), to: Graphene.CarbonComponents.Grid

  @doc false
  defdelegate header(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate header_global_action(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate header_menu(assigns), to: Graphene.CarbonComponents.HeaderMenu

  @doc false
  defdelegate header_menu_button(assigns), to: Graphene.CarbonComponents.HeaderMenu

  @doc false
  defdelegate header_menu_item(assigns), to: Graphene.CarbonComponents.HeaderMenu

  @doc false
  defdelegate header_name(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate header_nav(assigns), to: Graphene.CarbonComponents.HeaderNav

  @doc false
  defdelegate header_nav_item(assigns), to: Graphene.CarbonComponents.HeaderNav

  @doc false
  defdelegate header_panel(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate header_side_nav_items(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate heading(assigns), to: Graphene.CarbonComponents.Heading

  @doc false
  defdelegate icon(assigns), to: Graphene.CarbonComponents.Icon

  @doc false
  defdelegate icon_button(assigns), to: Graphene.CarbonComponents.Icon

  @doc false
  defdelegate icon_indicator(assigns), to: Graphene.CarbonComponents.Icon

  @doc false
  defdelegate inline_loading(assigns), to: Graphene.CarbonComponents.Inline

  @doc false
  defdelegate inline_notification(assigns), to: Graphene.CarbonComponents.Inline

  @doc false
  defdelegate layer(assigns), to: Graphene.CarbonComponents.Layer

  @doc false
  defdelegate link(assigns), to: Graphene.CarbonComponents.Link

  @doc false
  defdelegate list_item(assigns), to: Graphene.CarbonComponents.ListItem

  @doc false
  defdelegate loading(assigns), to: Graphene.CarbonComponents.Loading

  @doc false
  defdelegate menu(assigns), to: Graphene.CarbonComponents.Menu

  @doc false
  defdelegate menu_button(assigns), to: Graphene.CarbonComponents.Menu

  @doc false
  defdelegate menu_item(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate menu_item_divider(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate menu_item_group(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate menu_item_radio_group(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate menu_item_selectable(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate modal(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate modal_body(assigns), to: Graphene.CarbonComponents.ModalBody

  @doc false
  defdelegate modal_body_content(assigns), to: Graphene.CarbonComponents.ModalBody

  @doc false
  defdelegate modal_close_button(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate modal_footer(assigns), to: Graphene.CarbonComponents.ModalFooter

  @doc false
  defdelegate modal_footer_button(assigns), to: Graphene.CarbonComponents.ModalFooter

  @doc false
  defdelegate modal_header(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate modal_heading(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate modal_label(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate multi_select(assigns), to: Graphene.CarbonComponents.MultiSelect

  @doc false
  defdelegate multi_select_item(assigns), to: Graphene.CarbonComponents.MultiSelect

  @doc false
  defdelegate number_input(assigns), to: Graphene.CarbonComponents.NumberInput

  @doc false
  defdelegate number_input_skeleton(assigns), to: Graphene.CarbonComponents.NumberInput

  @doc false
  defdelegate operational_tag(assigns), to: Graphene.CarbonComponents.OperationalTag

  @doc false
  defdelegate ordered_list(assigns), to: Graphene.CarbonComponents.OrderedList

  @doc false
  defdelegate overflow_menu(assigns), to: Graphene.CarbonComponents.OverflowMenu

  @doc false
  defdelegate overflow_menu_body(assigns), to: Graphene.CarbonComponents.OverflowMenu

  @doc false
  defdelegate overflow_menu_item(assigns), to: Graphene.CarbonComponents.OverflowMenu

  @doc false
  defdelegate page_header(assigns), to: Graphene.CarbonComponents.PageHeader

  @doc false
  defdelegate page_header_breadcrumb(assigns), to: Graphene.CarbonComponents.PageHeader

  @doc false
  defdelegate page_header_content(assigns), to: Graphene.CarbonComponents.PageHeaderContent

  @doc false
  defdelegate page_header_content_text(assigns), to: Graphene.CarbonComponents.PageHeaderContent

  @doc false
  defdelegate page_header_hero_image(assigns), to: Graphene.CarbonComponents.PageHeader

  @doc false
  defdelegate page_header_tabs(assigns), to: Graphene.CarbonComponents.PageHeader

  @doc false
  defdelegate pagination(assigns), to: Graphene.CarbonComponents.Pagination

  @doc false
  defdelegate password_input(assigns), to: Graphene.CarbonComponents.PasswordInput

  @doc false
  defdelegate password_input_skeleton(assigns), to: Graphene.CarbonComponents.PasswordInput

  @doc false
  defdelegate popover(assigns), to: Graphene.CarbonComponents.Popover

  @doc false
  defdelegate popover_content(assigns), to: Graphene.CarbonComponents.Popover

  @doc false
  defdelegate progress_bar(assigns), to: Graphene.CarbonComponents.Progress

  @doc false
  defdelegate progress_indicator(assigns), to: Graphene.CarbonComponents.ProgressIndicator

  @doc false
  defdelegate progress_indicator_skeleton(assigns),
    to: Graphene.CarbonComponents.ProgressIndicator

  @doc false
  defdelegate progress_step(assigns), to: Graphene.CarbonComponents.ProgressStep

  @doc false
  defdelegate progress_step_skeleton(assigns), to: Graphene.CarbonComponents.ProgressStep

  @doc false
  defdelegate radio_button(assigns), to: Graphene.CarbonComponents.RadioButton

  @doc false
  defdelegate radio_button_group(assigns), to: Graphene.CarbonComponents.RadioButton

  @doc false
  defdelegate radio_button_skeleton(assigns), to: Graphene.CarbonComponents.RadioButton

  @doc false
  defdelegate radio_tile(assigns), to: Graphene.CarbonComponents.Radio

  @doc false
  defdelegate search(assigns), to: Graphene.CarbonComponents.Search

  @doc false
  defdelegate select(assigns), to: Graphene.CarbonComponents.Select

  @doc false
  defdelegate select_item(assigns), to: Graphene.CarbonComponents.SelectItem

  @doc false
  defdelegate select_item_group(assigns), to: Graphene.CarbonComponents.SelectItem

  @doc false
  defdelegate select_skeleton(assigns), to: Graphene.CarbonComponents.Select

  @doc false
  defdelegate selectable_tag(assigns), to: Graphene.CarbonComponents.Selectable

  @doc false
  defdelegate selectable_tile(assigns), to: Graphene.CarbonComponents.Selectable

  @doc false
  defdelegate shape_indicator(assigns), to: Graphene.CarbonComponents.ShapeIndicator

  @doc false
  defdelegate side_nav(assigns), to: Graphene.CarbonComponents.SideNav

  @doc false
  defdelegate side_nav_divider(assigns), to: Graphene.CarbonComponents.SideNav

  @doc false
  defdelegate side_nav_items(assigns), to: Graphene.CarbonComponents.SideNav

  @doc false
  defdelegate side_nav_link(assigns), to: Graphene.CarbonComponents.SideNav

  @doc false
  defdelegate side_nav_menu(assigns), to: Graphene.CarbonComponents.SideNavMenu

  @doc false
  defdelegate side_nav_menu_item(assigns), to: Graphene.CarbonComponents.SideNavMenu

  @doc false
  defdelegate side_panel(assigns), to: Graphene.CarbonComponents.Side

  @doc false
  defdelegate skeleton_icon(assigns), to: Graphene.CarbonComponents.Skeleton

  @doc false
  defdelegate skeleton_placeholder(assigns), to: Graphene.CarbonComponents.Skeleton

  @doc false
  defdelegate skeleton_text(assigns), to: Graphene.CarbonComponents.Skeleton

  @doc false
  defdelegate skip_to_content(assigns), to: Graphene.CarbonComponents.SkipToContent

  @doc false
  defdelegate slider(assigns), to: Graphene.CarbonComponents.Slider

  @doc false
  defdelegate slider_input(assigns), to: Graphene.CarbonComponents.Slider

  @doc false
  defdelegate slider_skeleton(assigns), to: Graphene.CarbonComponents.Slider

  @doc false
  defdelegate slug(assigns), to: Graphene.CarbonComponents.Slug

  @doc false
  defdelegate slug_action_button(assigns), to: Graphene.CarbonComponents.Slug

  @doc false
  defdelegate stack(assigns), to: Graphene.CarbonComponents.Stack

  @doc false
  defdelegate structured_list(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate structured_list_body(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate structured_list_cell(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate structured_list_head(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate structured_list_header_cell(assigns),
    to: Graphene.CarbonComponents.StructuredListHeaderCell

  @doc false
  defdelegate structured_list_header_cell_skeleton(assigns),
    to: Graphene.CarbonComponents.StructuredListHeaderCell

  @doc false
  defdelegate structured_list_header_row(assigns),
    to: Graphene.CarbonComponents.StructuredListHeader

  @doc false
  defdelegate structured_list_row(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate switcher(assigns), to: Graphene.CarbonComponents.Switcher

  @doc false
  defdelegate switcher_divider(assigns), to: Graphene.CarbonComponents.Switcher

  @doc false
  defdelegate switcher_item(assigns), to: Graphene.CarbonComponents.Switcher

  @doc false
  defdelegate tab(assigns), to: Graphene.CarbonComponents.Tab

  @doc false
  defdelegate tab_skeleton(assigns), to: Graphene.CarbonComponents.Tab

  @doc false
  defdelegate table(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_batch_actions(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_body(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_cell(assigns), to: Graphene.CarbonComponents.TableCell

  @doc false
  defdelegate table_cell_content(assigns), to: Graphene.CarbonComponents.TableCell

  @doc false
  defdelegate table_expanded_row(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_head(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_header_cell(assigns), to: Graphene.CarbonComponents.TableHeader

  @doc false
  defdelegate table_header_description(assigns), to: Graphene.CarbonComponents.TableHeader

  @doc false
  defdelegate table_header_row(assigns), to: Graphene.CarbonComponents.TableHeader

  @doc false
  defdelegate table_header_title(assigns), to: Graphene.CarbonComponents.TableHeader

  @doc false
  defdelegate table_row(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_skeleton(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_toolbar(assigns), to: Graphene.CarbonComponents.TableToolbar

  @doc false
  defdelegate table_toolbar_content(assigns), to: Graphene.CarbonComponents.TableToolbar

  @doc false
  defdelegate table_toolbar_search(assigns), to: Graphene.CarbonComponents.TableToolbar

  @doc false
  defdelegate tabs(assigns), to: Graphene.CarbonComponents.Tabs

  @doc false
  defdelegate tabs_skeleton(assigns), to: Graphene.CarbonComponents.Tabs

  @doc false
  defdelegate tag(assigns), to: Graphene.CarbonComponents.Tag

  @doc false
  defdelegate tag_skeleton(assigns), to: Graphene.CarbonComponents.Tag

  @doc false
  defdelegate tearsheet(assigns), to: Graphene.CarbonComponents.Tearsheet

  @doc false
  defdelegate text_input(assigns), to: Graphene.CarbonComponents.TextInput

  @doc false
  defdelegate text_input_skeleton(assigns), to: Graphene.CarbonComponents.TextInput

  @doc false
  defdelegate textarea(assigns), to: Graphene.CarbonComponents.Textarea

  @doc false
  defdelegate textarea_skeleton(assigns), to: Graphene.CarbonComponents.Textarea

  @doc false
  defdelegate tile(assigns), to: Graphene.CarbonComponents.Tile

  @doc false
  defdelegate tile_above_the_fold_content(assigns), to: Graphene.CarbonComponents.Tile

  @doc false
  defdelegate tile_below_the_fold_content(assigns), to: Graphene.CarbonComponents.Tile

  @doc false
  defdelegate tile_group(assigns), to: Graphene.CarbonComponents.Tile

  @doc false
  defdelegate time_picker(assigns), to: Graphene.CarbonComponents.TimePicker

  @doc false
  defdelegate time_picker_select(assigns), to: Graphene.CarbonComponents.TimePicker

  @doc false
  defdelegate toast_notification(assigns), to: Graphene.CarbonComponents.ToastNotification

  @doc false
  defdelegate toggle(assigns), to: Graphene.CarbonComponents.Toggle

  @doc false
  defdelegate toggle_skeleton(assigns), to: Graphene.CarbonComponents.Toggle

  @doc false
  defdelegate toggletip(assigns), to: Graphene.CarbonComponents.Toggletip

  @doc false
  defdelegate tooltip(assigns), to: Graphene.CarbonComponents.Tooltip

  @doc false
  defdelegate tooltip_content(assigns), to: Graphene.CarbonComponents.Tooltip

  @doc false
  defdelegate tree_node(assigns), to: Graphene.CarbonComponents.Tree

  @doc false
  defdelegate tree_view(assigns), to: Graphene.CarbonComponents.Tree

  @doc false
  defdelegate unordered_list(assigns), to: Graphene.CarbonComponents.UnorderedList

  @doc """
  Renders a Carbon data table with selection, sorting, filtering, and expansion
  support. This component owns interactive state to avoid LiveView flicker.

  ## Events

  * `graphene:table-row-selected` - Row selection changed.
  * `graphene:table-row-all-selected` - Select-all toggled.
  * `graphene:table-sorted` - Sort changed.
  * `graphene:table-filtered` - Filtered rows changed.
  * `graphene:table-search-input` - Search input changed.
  * `graphene:table-batch-cancel` - Batch selection canceled.
  """

  attr :id, :string, required: true
  attr :rows, :list, required: true
  attr :row_id, :any, default: nil, doc: "the function for generating the row id"
  attr :row_click, :any, default: nil, doc: "the function for handling phx-click on each row"

  attr :row_item, :any,
    default: &Function.identity/1,
    doc: "the function for mapping each row before calling the :col and :action slots"

  attr :selectable, :boolean, default: false, doc: "enable row selection"
  attr :sortable, :boolean, default: false, doc: "enable sorting UI on header cells"

  attr :selected_ids, :list,
    default: nil,
    doc:
      "selected row ids. When nil, the table keeps its internal selection state. Pass an explicit list to control selection."

  attr :selection_name, :string, default: nil, doc: "name attribute for row selection inputs"
  attr :selection_label, :string, default: "Select row", doc: "aria label for row selection"
  attr :radio, :boolean, default: false, doc: "use radio selection instead of checkboxes"
  attr :size, :string, default: "lg", values: ["xs", "sm", "md", "lg", "xl"], doc: "table size"
  attr :expandable, :boolean, default: false, doc: "enable expandable rows"
  attr :batch_expansion, :boolean, default: false, doc: "enable batch expansion control"

  attr :overflow_menu_on_hover, :boolean,
    default: false,
    doc: "show overflow menu only on hover"

  attr :use_zebra_styles, :boolean, default: true, doc: "enable zebra striping"
  attr :use_static_width, :boolean, default: false, doc: "use static table width"
  attr :with_row_ai_labels, :boolean, default: false, doc: "enable AI labels in rows"
  attr :with_row_slugs, :boolean, default: false, doc: "enable slugs in rows"
  attr :locale, :string, default: nil, doc: "table locale"
  attr :filter_rows, :any, default: nil, doc: "custom filter rows function"

  attr :phx_update, :any,
    default: "ignore",
    doc:
      "phx-update behavior for the table root. Defaults to \"ignore\" so LiveView does not patch the table subtree after client-side sorting/filtering. Set to nil or false to allow normal patching."

  attr :on_row_selected, :any, default: nil, doc: "callback for row selection events"
  attr :on_row_all_selected, :any, default: nil, doc: "callback for select-all events"
  attr :on_sorted, :any, default: nil, doc: "callback for sort events"
  attr :on_filtered, :any, default: nil, doc: "callback for filter events"
  attr :on_search, :any, default: nil, doc: "callback for search events"
  attr :on_batch_cancel, :any, default: nil, doc: "callback for batch cancel events"

  slot :col, required: true do
    attr :label, :any
  end

  slot :action, doc: "the slot for showing user actions in the last table column"
  slot :title, doc: "table title"
  slot :description, doc: "table description"
  slot :toolbar, doc: "table toolbar contents"

  slot :row_decorator, doc: "content injected before row cells" do
    attr :class, :string
  end

  slot :expanded_row, doc: "content rendered as expanded rows"

  def data_table(assigns) do
    assigns =
      assigns
      |> table_assigns()
      |> assign(:component_id, "#{assigns.id}-component")

    ~H"""
    <.live_component
      module={DataTableComponent}
      id={@component_id}
      table_id={@id}
      rows={@rows}
      row_id={@row_id}
      row_click={@row_click}
      row_item={@row_item}
      col={@col}
      action={@action}
      selectable={@selectable}
      sortable={@sortable}
      selected_ids={@selected_ids}
      selection_name={@selection_name}
      selection_label={@selection_label}
      radio={@radio}
      size={@size}
      expandable={@expandable}
      batch_expansion={@batch_expansion}
      overflow_menu_on_hover={@overflow_menu_on_hover}
      use_zebra_styles={@use_zebra_styles}
      use_static_width={@use_static_width}
      with_row_ai_labels={@with_row_ai_labels}
      with_row_slugs={@with_row_slugs}
      locale={@locale}
      filter_rows={@filter_rows}
      phx_update={@phx_update}
      on_row_selected={@on_row_selected}
      on_row_all_selected={@on_row_all_selected}
      on_sorted={@on_sorted}
      on_filtered={@on_filtered}
      on_search={@on_search}
      on_batch_cancel={@on_batch_cancel}
      title={@title}
      description={@description}
      toolbar={@toolbar}
      row_decorator={@row_decorator}
      expanded_row={@expanded_row}
    />
    """
  end

  @doc """
  File uploader wrapper for Carbon web components.
  """
  attr :field, Phoenix.HTML.FormField, default: nil
  attr :form, :string, default: nil
  attr :id, :string, default: nil
  attr :name, :string, default: nil
  attr :value, :any, default: nil
  attr :disabled, :boolean, default: false
  attr :label_description, :string, default: nil
  attr :label_title, :string, default: nil
  attr :file_input_name, :string, default: nil
  attr :form_event, :string, default: nil
  attr :rest, :global

  slot :button do
    attr :label, :string
    attr :accept, :string
    attr :button_kind, :string
    attr :disabled, :boolean
    attr :multiple, :boolean
    attr :name, :string
    attr :size, :string
    attr :attrs, :map
  end

  slot :drop_container do
    attr :accept, :string
    attr :disabled, :boolean
    attr :multiple, :boolean
    attr :name, :string
    attr :attrs, :map
  end

  slot :item do
    attr :state, :string
    attr :invalid, :boolean
    attr :icon_description, :string
    attr :attrs, :map
  end

  slot :inner_block

  def file_uploader(assigns) do
    FormComponents.file_uploader(assigns)
  end

  @doc """
  UI shell layout that renders header, side nav, and content slots.
  """
  attr :rest, :global
  attr :content_class, :string, default: nil
  slot :skip_to_content
  slot :header
  slot :side_nav
  slot :content

  def ui_shell(assigns) do
    content_class =
      case assigns[:content_class] do
        nil ->
          "cds--content"

        "" ->
          "cds--content"

        class when is_binary(class) ->
          if String.contains?(class, "cds--content") do
            class
          else
            class <> " cds--content"
          end
      end

    assigns = assign(assigns, :content_class, content_class)

    ~H"""
    <div {@rest}>
      {render_slot(@skip_to_content)}
      {render_slot(@header)}
      {render_slot(@side_nav)}
      <main class={@content_class}>
        {render_slot(@content)}
      </main>
    </div>
    """
  end

  defp table_assigns(assigns) do
    assigns =
      case Map.get(assigns, :phx_update) do
        false -> Map.put(assigns, :phx_update, nil)
        "" -> Map.put(assigns, :phx_update, nil)
        _ -> assigns
      end

    case assigns do
      %{rows: %Phoenix.LiveView.LiveStream{}} ->
        assign(assigns, row_id: assigns.row_id || fn {id, _item} -> id end)

      _ ->
        assigns
    end
  end
end
