defmodule Graphene.CarbonComponents do
  @moduledoc """
  Autogenerated module. Do not edit directly.

  Graphene.CarbonComponents is autogenerated from Carbon web components metadata.

  High-level Carbon components built on top of internal low-level components.

  These wrappers avoid direct use of <cds-*> tags and expose a single
  namespace for Carbon web components. Component implementations live in
  grouped modules under Graphene.CarbonComponents.* and this module
  delegates to them.
  """

  use Phoenix.Component

  defmacro __using__(_opts) do
    quote do
      import Graphene.CarbonComponents,
        only: [table: 1, table_live: 1, file_uploader: 1, ui_shell: 1]

      import Graphene.CarbonComponents.Accordion
      import Graphene.CarbonComponents.ActionableNotification
      import Graphene.CarbonComponents.AiLabel
      import Graphene.CarbonComponents.AiSkeleton
      import Graphene.CarbonComponents.BadgeIndicator
      import Graphene.CarbonComponents.Breadcrumb
      import Graphene.CarbonComponents.Button
      import Graphene.CarbonComponents.ButtonSet
      import Graphene.CarbonComponents.CalloutNotification
      import Graphene.CarbonComponents.ChatButton
      import Graphene.CarbonComponents.Checkbox
      import Graphene.CarbonComponents.ClickableTile
      import Graphene.CarbonComponents.CodeSnippet
      import Graphene.CarbonComponents.Column
      import Graphene.CarbonComponents.Combo
      import Graphene.CarbonComponents.ComboBox
      import Graphene.CarbonComponents.ContainedList
      import Graphene.CarbonComponents.ContentSwitcher
      import Graphene.CarbonComponents.Copy
      import Graphene.CarbonComponents.DatePicker
      import Graphene.CarbonComponents.DatePickerInput
      import Graphene.CarbonComponents.DefinitionTooltip
      import Graphene.CarbonComponents.DismissibleTag
      import Graphene.CarbonComponents.Dropdown
      import Graphene.CarbonComponents.ExpandableTile
      import Graphene.CarbonComponents.FeatureFlags
      import Graphene.CarbonComponents.FileUploader
      import Graphene.CarbonComponents.FluidNumberInput
      import Graphene.CarbonComponents.FluidSearch
      import Graphene.CarbonComponents.FluidSelect
      import Graphene.CarbonComponents.FluidTextInput
      import Graphene.CarbonComponents.FluidTextarea
      import Graphene.CarbonComponents.FluidTimePicker
      import Graphene.CarbonComponents.Form
      import Graphene.CarbonComponents.Grid
      import Graphene.CarbonComponents.Header
      import Graphene.CarbonComponents.HeaderMenu
      import Graphene.CarbonComponents.HeaderNav
      import Graphene.CarbonComponents.Heading
      import Graphene.CarbonComponents.Icon
      import Graphene.CarbonComponents.Inline
      import Graphene.CarbonComponents.Layer
      import Graphene.CarbonComponents.Link
      import Graphene.CarbonComponents.ListItem
      import Graphene.CarbonComponents.Loading
      import Graphene.CarbonComponents.Menu
      import Graphene.CarbonComponents.MenuItem
      import Graphene.CarbonComponents.Modal
      import Graphene.CarbonComponents.ModalBody
      import Graphene.CarbonComponents.ModalFooter
      import Graphene.CarbonComponents.MultiSelect
      import Graphene.CarbonComponents.NumberInput
      import Graphene.CarbonComponents.OperationalTag
      import Graphene.CarbonComponents.OrderedList
      import Graphene.CarbonComponents.OverflowMenu
      import Graphene.CarbonComponents.PageHeader
      import Graphene.CarbonComponents.PageHeaderContent
      import Graphene.CarbonComponents.Pagination
      import Graphene.CarbonComponents.PasswordInput
      import Graphene.CarbonComponents.Popover
      import Graphene.CarbonComponents.Progress
      import Graphene.CarbonComponents.ProgressIndicator
      import Graphene.CarbonComponents.ProgressStep
      import Graphene.CarbonComponents.Radio
      import Graphene.CarbonComponents.RadioButton
      import Graphene.CarbonComponents.Search
      import Graphene.CarbonComponents.Select
      import Graphene.CarbonComponents.SelectItem
      import Graphene.CarbonComponents.Selectable
      import Graphene.CarbonComponents.ShapeIndicator
      import Graphene.CarbonComponents.Side
      import Graphene.CarbonComponents.SideNav
      import Graphene.CarbonComponents.SideNavMenu
      import Graphene.CarbonComponents.Skeleton
      import Graphene.CarbonComponents.SkipToContent
      import Graphene.CarbonComponents.Slider
      import Graphene.CarbonComponents.Slug
      import Graphene.CarbonComponents.Stack
      import Graphene.CarbonComponents.StructuredList
      import Graphene.CarbonComponents.StructuredListHeader
      import Graphene.CarbonComponents.StructuredListHeaderCell
      import Graphene.CarbonComponents.Switcher
      import Graphene.CarbonComponents.Tab
      import Graphene.CarbonComponents.Table
      import Graphene.CarbonComponents.TableCell
      import Graphene.CarbonComponents.TableHeader
      import Graphene.CarbonComponents.TableToolbar
      import Graphene.CarbonComponents.Tabs
      import Graphene.CarbonComponents.Tag
      import Graphene.CarbonComponents.Tearsheet
      import Graphene.CarbonComponents.TextInput
      import Graphene.CarbonComponents.Textarea
      import Graphene.CarbonComponents.Tile
      import Graphene.CarbonComponents.TimePicker
      import Graphene.CarbonComponents.ToastNotification
      import Graphene.CarbonComponents.Toggle
      import Graphene.CarbonComponents.Toggletip
      import Graphene.CarbonComponents.Tooltip
      import Graphene.CarbonComponents.Tree
      import Graphene.CarbonComponents.UnorderedList
    end
  end

  @doc false
  defdelegate accordion(assigns), to: Graphene.CarbonComponents.Accordion

  @doc false
  defdelegate accordion_item(assigns), to: Graphene.CarbonComponents.Accordion

  @doc false
  defdelegate accordion_skeleton(assigns), to: Graphene.CarbonComponents.Accordion

  @doc false
  defdelegate actionable_notification(assigns),
    to: Graphene.CarbonComponents.ActionableNotification

  @doc false
  defdelegate actionable_notification_button(assigns),
    to: Graphene.CarbonComponents.ActionableNotification

  @doc false
  defdelegate ai_label(assigns), to: Graphene.CarbonComponents.AiLabel

  @doc false
  defdelegate ai_label_action_button(assigns), to: Graphene.CarbonComponents.AiLabel

  @doc false
  defdelegate ai_skeleton_icon(assigns), to: Graphene.CarbonComponents.AiSkeleton

  @doc false
  defdelegate ai_skeleton_placeholder(assigns), to: Graphene.CarbonComponents.AiSkeleton

  @doc false
  defdelegate ai_skeleton_text(assigns), to: Graphene.CarbonComponents.AiSkeleton

  @doc false
  defdelegate badge_indicator(assigns), to: Graphene.CarbonComponents.BadgeIndicator

  @doc false
  defdelegate breadcrumb(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate breadcrumb_item(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate breadcrumb_link(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate breadcrumb_overflow_menu(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate breadcrumb_skeleton(assigns), to: Graphene.CarbonComponents.Breadcrumb

  @doc false
  defdelegate button(assigns), to: Graphene.CarbonComponents.Button

  @doc false
  defdelegate button_set(assigns), to: Graphene.CarbonComponents.ButtonSet

  @doc false
  defdelegate button_set_base(assigns), to: Graphene.CarbonComponents.ButtonSet

  @doc false
  defdelegate button_skeleton(assigns), to: Graphene.CarbonComponents.Button

  @doc false
  defdelegate callout_notification(assigns), to: Graphene.CarbonComponents.CalloutNotification

  @doc false
  defdelegate chat_button(assigns), to: Graphene.CarbonComponents.ChatButton

  @doc false
  defdelegate chat_button_skeleton(assigns), to: Graphene.CarbonComponents.ChatButton

  @doc false
  defdelegate checkbox(assigns), to: Graphene.CarbonComponents.Checkbox

  @doc false
  defdelegate checkbox_group(assigns), to: Graphene.CarbonComponents.Checkbox

  @doc false
  defdelegate checkbox_skeleton(assigns), to: Graphene.CarbonComponents.Checkbox

  @doc false
  defdelegate clickable_tile(assigns), to: Graphene.CarbonComponents.ClickableTile

  @doc false
  defdelegate code_snippet(assigns), to: Graphene.CarbonComponents.CodeSnippet

  @doc false
  defdelegate code_snippet_skeleton(assigns), to: Graphene.CarbonComponents.CodeSnippet

  @doc false
  defdelegate column(assigns), to: Graphene.CarbonComponents.Column

  @doc false
  defdelegate column_hang(assigns), to: Graphene.CarbonComponents.Column

  @doc false
  defdelegate combo_box(assigns), to: Graphene.CarbonComponents.ComboBox

  @doc false
  defdelegate combo_box_item(assigns), to: Graphene.CarbonComponents.ComboBox

  @doc false
  defdelegate combo_button(assigns), to: Graphene.CarbonComponents.Combo

  @doc false
  defdelegate contained_list(assigns), to: Graphene.CarbonComponents.ContainedList

  @doc false
  defdelegate contained_list_description(assigns), to: Graphene.CarbonComponents.ContainedList

  @doc false
  defdelegate contained_list_item(assigns), to: Graphene.CarbonComponents.ContainedList

  @doc false
  defdelegate content_switcher(assigns), to: Graphene.CarbonComponents.ContentSwitcher

  @doc false
  defdelegate content_switcher_item(assigns), to: Graphene.CarbonComponents.ContentSwitcher

  @doc false
  defdelegate copy(assigns), to: Graphene.CarbonComponents.Copy

  @doc false
  defdelegate copy_button(assigns), to: Graphene.CarbonComponents.Copy

  @doc false
  defdelegate date_picker(assigns), to: Graphene.CarbonComponents.DatePicker

  @doc false
  defdelegate date_picker_input(assigns), to: Graphene.CarbonComponents.DatePickerInput

  @doc false
  defdelegate date_picker_input_skeleton(assigns), to: Graphene.CarbonComponents.DatePickerInput

  @doc false
  defdelegate definition_tooltip(assigns), to: Graphene.CarbonComponents.DefinitionTooltip

  @doc false
  defdelegate dismissible_tag(assigns), to: Graphene.CarbonComponents.DismissibleTag

  @doc false
  defdelegate dropdown(assigns), to: Graphene.CarbonComponents.Dropdown

  @doc false
  defdelegate dropdown_item(assigns), to: Graphene.CarbonComponents.Dropdown

  @doc false
  defdelegate dropdown_skeleton(assigns), to: Graphene.CarbonComponents.Dropdown

  @doc false
  defdelegate expandable_tile(assigns), to: Graphene.CarbonComponents.ExpandableTile

  @doc false
  defdelegate feature_flags(assigns), to: Graphene.CarbonComponents.FeatureFlags

  @doc false
  defdelegate file_uploader_button(assigns), to: Graphene.CarbonComponents.FileUploader

  @doc false
  defdelegate file_uploader_drop_container(assigns), to: Graphene.CarbonComponents.FileUploader

  @doc false
  defdelegate file_uploader_item(assigns), to: Graphene.CarbonComponents.FileUploader

  @doc false
  defdelegate file_uploader_skeleton(assigns), to: Graphene.CarbonComponents.FileUploader

  @doc false
  defdelegate fluid_number_input(assigns), to: Graphene.CarbonComponents.FluidNumberInput

  @doc false
  defdelegate fluid_number_input_skeleton(assigns), to: Graphene.CarbonComponents.FluidNumberInput

  @doc false
  defdelegate fluid_search(assigns), to: Graphene.CarbonComponents.FluidSearch

  @doc false
  defdelegate fluid_search_skeleton(assigns), to: Graphene.CarbonComponents.FluidSearch

  @doc false
  defdelegate fluid_select(assigns), to: Graphene.CarbonComponents.FluidSelect

  @doc false
  defdelegate fluid_select_skeleton(assigns), to: Graphene.CarbonComponents.FluidSelect

  @doc false
  defdelegate fluid_text_input(assigns), to: Graphene.CarbonComponents.FluidTextInput

  @doc false
  defdelegate fluid_text_input_skeleton(assigns), to: Graphene.CarbonComponents.FluidTextInput

  @doc false
  defdelegate fluid_textarea(assigns), to: Graphene.CarbonComponents.FluidTextarea

  @doc false
  defdelegate fluid_textarea_skeleton(assigns), to: Graphene.CarbonComponents.FluidTextarea

  @doc false
  defdelegate fluid_time_picker(assigns), to: Graphene.CarbonComponents.FluidTimePicker

  @doc false
  defdelegate fluid_time_picker_select(assigns), to: Graphene.CarbonComponents.FluidTimePicker

  @doc false
  defdelegate fluid_time_picker_skeleton(assigns), to: Graphene.CarbonComponents.FluidTimePicker

  @doc false
  defdelegate form(assigns), to: Graphene.CarbonComponents.Form

  @doc false
  defdelegate form_group(assigns), to: Graphene.CarbonComponents.Form

  @doc false
  defdelegate form_item(assigns), to: Graphene.CarbonComponents.Form

  @doc false
  defdelegate grid(assigns), to: Graphene.CarbonComponents.Grid

  @doc false
  defdelegate header(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate header_global_action(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate header_menu(assigns), to: Graphene.CarbonComponents.HeaderMenu

  @doc false
  defdelegate header_menu_button(assigns), to: Graphene.CarbonComponents.HeaderMenu

  @doc false
  defdelegate header_menu_item(assigns), to: Graphene.CarbonComponents.HeaderMenu

  @doc false
  defdelegate header_name(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate header_nav(assigns), to: Graphene.CarbonComponents.HeaderNav

  @doc false
  defdelegate header_nav_item(assigns), to: Graphene.CarbonComponents.HeaderNav

  @doc false
  defdelegate header_panel(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate header_side_nav_items(assigns), to: Graphene.CarbonComponents.Header

  @doc false
  defdelegate heading(assigns), to: Graphene.CarbonComponents.Heading

  @doc false
  defdelegate icon(assigns), to: Graphene.CarbonComponents.Icon

  @doc false
  defdelegate icon_button(assigns), to: Graphene.CarbonComponents.Icon

  @doc false
  defdelegate icon_indicator(assigns), to: Graphene.CarbonComponents.Icon

  @doc false
  defdelegate inline_loading(assigns), to: Graphene.CarbonComponents.Inline

  @doc false
  defdelegate inline_notification(assigns), to: Graphene.CarbonComponents.Inline

  @doc false
  defdelegate layer(assigns), to: Graphene.CarbonComponents.Layer

  @doc false
  defdelegate link(assigns), to: Graphene.CarbonComponents.Link

  @doc false
  defdelegate list_item(assigns), to: Graphene.CarbonComponents.ListItem

  @doc false
  defdelegate loading(assigns), to: Graphene.CarbonComponents.Loading

  @doc false
  defdelegate menu(assigns), to: Graphene.CarbonComponents.Menu

  @doc false
  defdelegate menu_button(assigns), to: Graphene.CarbonComponents.Menu

  @doc false
  defdelegate menu_item(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate menu_item_divider(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate menu_item_group(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate menu_item_radio_group(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate menu_item_selectable(assigns), to: Graphene.CarbonComponents.MenuItem

  @doc false
  defdelegate modal(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate modal_body(assigns), to: Graphene.CarbonComponents.ModalBody

  @doc false
  defdelegate modal_body_content(assigns), to: Graphene.CarbonComponents.ModalBody

  @doc false
  defdelegate modal_close_button(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate modal_footer(assigns), to: Graphene.CarbonComponents.ModalFooter

  @doc false
  defdelegate modal_footer_button(assigns), to: Graphene.CarbonComponents.ModalFooter

  @doc false
  defdelegate modal_header(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate modal_heading(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate modal_label(assigns), to: Graphene.CarbonComponents.Modal

  @doc false
  defdelegate multi_select(assigns), to: Graphene.CarbonComponents.MultiSelect

  @doc false
  defdelegate multi_select_item(assigns), to: Graphene.CarbonComponents.MultiSelect

  @doc false
  defdelegate number_input(assigns), to: Graphene.CarbonComponents.NumberInput

  @doc false
  defdelegate number_input_skeleton(assigns), to: Graphene.CarbonComponents.NumberInput

  @doc false
  defdelegate operational_tag(assigns), to: Graphene.CarbonComponents.OperationalTag

  @doc false
  defdelegate ordered_list(assigns), to: Graphene.CarbonComponents.OrderedList

  @doc false
  defdelegate overflow_menu(assigns), to: Graphene.CarbonComponents.OverflowMenu

  @doc false
  defdelegate overflow_menu_body(assigns), to: Graphene.CarbonComponents.OverflowMenu

  @doc false
  defdelegate overflow_menu_item(assigns), to: Graphene.CarbonComponents.OverflowMenu

  @doc false
  defdelegate page_header(assigns), to: Graphene.CarbonComponents.PageHeader

  @doc false
  defdelegate page_header_breadcrumb(assigns), to: Graphene.CarbonComponents.PageHeader

  @doc false
  defdelegate page_header_content(assigns), to: Graphene.CarbonComponents.PageHeaderContent

  @doc false
  defdelegate page_header_content_text(assigns), to: Graphene.CarbonComponents.PageHeaderContent

  @doc false
  defdelegate page_header_hero_image(assigns), to: Graphene.CarbonComponents.PageHeader

  @doc false
  defdelegate page_header_tabs(assigns), to: Graphene.CarbonComponents.PageHeader

  @doc false
  defdelegate pagination(assigns), to: Graphene.CarbonComponents.Pagination

  @doc false
  defdelegate pagination_nav(assigns), to: Graphene.CarbonComponents.Pagination

  @doc false
  defdelegate password_input(assigns), to: Graphene.CarbonComponents.PasswordInput

  @doc false
  defdelegate password_input_skeleton(assigns), to: Graphene.CarbonComponents.PasswordInput

  @doc false
  defdelegate popover(assigns), to: Graphene.CarbonComponents.Popover

  @doc false
  defdelegate popover_content(assigns), to: Graphene.CarbonComponents.Popover

  @doc false
  defdelegate progress_bar(assigns), to: Graphene.CarbonComponents.Progress

  @doc false
  defdelegate progress_indicator(assigns), to: Graphene.CarbonComponents.ProgressIndicator

  @doc false
  defdelegate progress_indicator_skeleton(assigns),
    to: Graphene.CarbonComponents.ProgressIndicator

  @doc false
  defdelegate progress_step(assigns), to: Graphene.CarbonComponents.ProgressStep

  @doc false
  defdelegate progress_step_skeleton(assigns), to: Graphene.CarbonComponents.ProgressStep

  @doc false
  defdelegate radio_button(assigns), to: Graphene.CarbonComponents.RadioButton

  @doc false
  defdelegate radio_button_group(assigns), to: Graphene.CarbonComponents.RadioButton

  @doc false
  defdelegate radio_button_skeleton(assigns), to: Graphene.CarbonComponents.RadioButton

  @doc false
  defdelegate radio_tile(assigns), to: Graphene.CarbonComponents.Radio

  @doc false
  defdelegate search(assigns), to: Graphene.CarbonComponents.Search

  @doc false
  defdelegate select(assigns), to: Graphene.CarbonComponents.Select

  @doc false
  defdelegate select_item(assigns), to: Graphene.CarbonComponents.SelectItem

  @doc false
  defdelegate select_item_group(assigns), to: Graphene.CarbonComponents.SelectItem

  @doc false
  defdelegate select_skeleton(assigns), to: Graphene.CarbonComponents.Select

  @doc false
  defdelegate selectable_tag(assigns), to: Graphene.CarbonComponents.Selectable

  @doc false
  defdelegate selectable_tile(assigns), to: Graphene.CarbonComponents.Selectable

  @doc false
  defdelegate shape_indicator(assigns), to: Graphene.CarbonComponents.ShapeIndicator

  @doc false
  defdelegate side_nav(assigns), to: Graphene.CarbonComponents.SideNav

  @doc false
  defdelegate side_nav_divider(assigns), to: Graphene.CarbonComponents.SideNav

  @doc false
  defdelegate side_nav_items(assigns), to: Graphene.CarbonComponents.SideNav

  @doc false
  defdelegate side_nav_link(assigns), to: Graphene.CarbonComponents.SideNav

  @doc false
  defdelegate side_nav_menu(assigns), to: Graphene.CarbonComponents.SideNavMenu

  @doc false
  defdelegate side_nav_menu_item(assigns), to: Graphene.CarbonComponents.SideNavMenu

  @doc false
  defdelegate side_panel(assigns), to: Graphene.CarbonComponents.Side

  @doc false
  defdelegate skeleton_icon(assigns), to: Graphene.CarbonComponents.Skeleton

  @doc false
  defdelegate skeleton_placeholder(assigns), to: Graphene.CarbonComponents.Skeleton

  @doc false
  defdelegate skeleton_text(assigns), to: Graphene.CarbonComponents.Skeleton

  @doc false
  defdelegate skip_to_content(assigns), to: Graphene.CarbonComponents.SkipToContent

  @doc false
  defdelegate slider(assigns), to: Graphene.CarbonComponents.Slider

  @doc false
  defdelegate slider_input(assigns), to: Graphene.CarbonComponents.Slider

  @doc false
  defdelegate slider_skeleton(assigns), to: Graphene.CarbonComponents.Slider

  @doc false
  defdelegate slug(assigns), to: Graphene.CarbonComponents.Slug

  @doc false
  defdelegate slug_action_button(assigns), to: Graphene.CarbonComponents.Slug

  @doc false
  defdelegate stack(assigns), to: Graphene.CarbonComponents.Stack

  @doc false
  defdelegate structured_list(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate structured_list_body(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate structured_list_cell(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate structured_list_head(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate structured_list_header_cell(assigns),
    to: Graphene.CarbonComponents.StructuredListHeaderCell

  @doc false
  defdelegate structured_list_header_cell_skeleton(assigns),
    to: Graphene.CarbonComponents.StructuredListHeaderCell

  @doc false
  defdelegate structured_list_header_row(assigns),
    to: Graphene.CarbonComponents.StructuredListHeader

  @doc false
  defdelegate structured_list_row(assigns), to: Graphene.CarbonComponents.StructuredList

  @doc false
  defdelegate switcher(assigns), to: Graphene.CarbonComponents.Switcher

  @doc false
  defdelegate switcher_divider(assigns), to: Graphene.CarbonComponents.Switcher

  @doc false
  defdelegate switcher_item(assigns), to: Graphene.CarbonComponents.Switcher

  @doc false
  defdelegate tab(assigns), to: Graphene.CarbonComponents.Tab

  @doc false
  defdelegate tab_skeleton(assigns), to: Graphene.CarbonComponents.Tab

  @doc false
  defdelegate table_batch_actions(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_body(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_cell(assigns), to: Graphene.CarbonComponents.TableCell

  @doc false
  defdelegate table_cell_content(assigns), to: Graphene.CarbonComponents.TableCell

  @doc false
  defdelegate table_element(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_expanded_row(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_head(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_header_cell(assigns), to: Graphene.CarbonComponents.TableHeader

  @doc false
  defdelegate table_header_description(assigns), to: Graphene.CarbonComponents.TableHeader

  @doc false
  defdelegate table_header_row(assigns), to: Graphene.CarbonComponents.TableHeader

  @doc false
  defdelegate table_header_title(assigns), to: Graphene.CarbonComponents.TableHeader

  @doc false
  defdelegate table_row(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_skeleton(assigns), to: Graphene.CarbonComponents.Table

  @doc false
  defdelegate table_toolbar(assigns), to: Graphene.CarbonComponents.TableToolbar

  @doc false
  defdelegate table_toolbar_content(assigns), to: Graphene.CarbonComponents.TableToolbar

  @doc false
  defdelegate table_toolbar_search(assigns), to: Graphene.CarbonComponents.TableToolbar

  @doc false
  defdelegate tabs(assigns), to: Graphene.CarbonComponents.Tabs

  @doc false
  defdelegate tabs_skeleton(assigns), to: Graphene.CarbonComponents.Tabs

  @doc false
  defdelegate tag(assigns), to: Graphene.CarbonComponents.Tag

  @doc false
  defdelegate tag_skeleton(assigns), to: Graphene.CarbonComponents.Tag

  @doc false
  defdelegate tearsheet(assigns), to: Graphene.CarbonComponents.Tearsheet

  @doc false
  defdelegate text_input(assigns), to: Graphene.CarbonComponents.TextInput

  @doc false
  defdelegate text_input_skeleton(assigns), to: Graphene.CarbonComponents.TextInput

  @doc false
  defdelegate textarea(assigns), to: Graphene.CarbonComponents.Textarea

  @doc false
  defdelegate textarea_skeleton(assigns), to: Graphene.CarbonComponents.Textarea

  @doc false
  defdelegate tile(assigns), to: Graphene.CarbonComponents.Tile

  @doc false
  defdelegate tile_above_the_fold_content(assigns), to: Graphene.CarbonComponents.Tile

  @doc false
  defdelegate tile_below_the_fold_content(assigns), to: Graphene.CarbonComponents.Tile

  @doc false
  defdelegate tile_group(assigns), to: Graphene.CarbonComponents.Tile

  @doc false
  defdelegate time_picker(assigns), to: Graphene.CarbonComponents.TimePicker

  @doc false
  defdelegate time_picker_select(assigns), to: Graphene.CarbonComponents.TimePicker

  @doc false
  defdelegate toast_notification(assigns), to: Graphene.CarbonComponents.ToastNotification

  @doc false
  defdelegate toggle(assigns), to: Graphene.CarbonComponents.Toggle

  @doc false
  defdelegate toggle_skeleton(assigns), to: Graphene.CarbonComponents.Toggle

  @doc false
  defdelegate toggletip(assigns), to: Graphene.CarbonComponents.Toggletip

  @doc false
  defdelegate tooltip(assigns), to: Graphene.CarbonComponents.Tooltip

  @doc false
  defdelegate tooltip_content(assigns), to: Graphene.CarbonComponents.Tooltip

  @doc false
  defdelegate tree_node(assigns), to: Graphene.CarbonComponents.Tree

  @doc false
  defdelegate tree_view(assigns), to: Graphene.CarbonComponents.Tree

  @doc false
  defdelegate unordered_list(assigns), to: Graphene.CarbonComponents.UnorderedList

  defdelegate table(assigns), to: Graphene.CarbonComponents.Custom.Table
  defdelegate table_live(assigns), to: Graphene.CarbonComponents.Custom.DataTable
  defdelegate file_uploader(assigns), to: Graphene.CarbonComponents.Custom.FileUploader
  defdelegate ui_shell(assigns), to: Graphene.CarbonComponents.Custom.UiShell
  defdelegate data_table(assigns), to: Graphene.CarbonComponents.Custom.DataTable
end
