defmodule Graphene.ProductComponents do
  @moduledoc """
  Autogenerated module. Do not edit directly.

  Graphene.ProductComponents is autogenerated from IBM Products web components metadata.

  High-level Product components built on top of internal low-level components.

  These wrappers avoid direct use of <c4p-*> tags and expose a single
  namespace for IBM Products web components. Component implementations live in
  grouped modules under Graphene.ProductComponents.* and this module
  delegates to them.
  """

  use Phoenix.Component

  defmacro __using__(_opts) do
    quote do
      import Graphene.ProductComponents.AboutModal
      import Graphene.ProductComponents.BigNumber
      import Graphene.ProductComponents.Checklist
      import Graphene.ProductComponents.Coachmark
      import Graphene.ProductComponents.FullPageError
      import Graphene.ProductComponents.GuideBanner
      import Graphene.ProductComponents.InterstitialScreen
      import Graphene.ProductComponents.InterstitialScreenBody
      import Graphene.ProductComponents.Notification
      import Graphene.ProductComponents.OptionsTile
      import Graphene.ProductComponents.PageHeader
      import Graphene.ProductComponents.PageHeaderContent
      import Graphene.ProductComponents.SidePanel
      import Graphene.ProductComponents.Tearsheet
      import Graphene.ProductComponents.TruncatedText
      import Graphene.ProductComponents.UserAvatar
    end
  end

  @doc false
  defdelegate about_modal(assigns), to: Graphene.ProductComponents.AboutModal

  @doc false
  defdelegate big_number(assigns), to: Graphene.ProductComponents.BigNumber

  @doc false
  defdelegate big_number_skeleton(assigns), to: Graphene.ProductComponents.BigNumber

  @doc false
  defdelegate checklist(assigns), to: Graphene.ProductComponents.Checklist

  @doc false
  defdelegate checklist_chart(assigns), to: Graphene.ProductComponents.Checklist

  @doc false
  defdelegate checklist_group(assigns), to: Graphene.ProductComponents.Checklist

  @doc false
  defdelegate checklist_icon(assigns), to: Graphene.ProductComponents.Checklist

  @doc false
  defdelegate checklist_item(assigns), to: Graphene.ProductComponents.Checklist

  @doc false
  defdelegate coachmark(assigns), to: Graphene.ProductComponents.Coachmark

  @doc false
  defdelegate coachmark_beacon(assigns), to: Graphene.ProductComponents.Coachmark

  @doc false
  defdelegate coachmark_body(assigns), to: Graphene.ProductComponents.Coachmark

  @doc false
  defdelegate coachmark_header(assigns), to: Graphene.ProductComponents.Coachmark

  @doc false
  defdelegate coachmark_tagline(assigns), to: Graphene.ProductComponents.Coachmark

  @doc false
  defdelegate full_page_error(assigns), to: Graphene.ProductComponents.FullPageError

  @doc false
  defdelegate guide_banner(assigns), to: Graphene.ProductComponents.GuideBanner

  @doc false
  defdelegate guide_banner_element(assigns), to: Graphene.ProductComponents.GuideBanner

  @doc false
  defdelegate interstitial_screen(assigns), to: Graphene.ProductComponents.InterstitialScreen

  @doc false
  defdelegate interstitial_screen_body(assigns),
    to: Graphene.ProductComponents.InterstitialScreenBody

  @doc false
  defdelegate interstitial_screen_body_item(assigns),
    to: Graphene.ProductComponents.InterstitialScreenBody

  @doc false
  defdelegate interstitial_screen_footer(assigns),
    to: Graphene.ProductComponents.InterstitialScreen

  @doc false
  defdelegate interstitial_screen_header(assigns),
    to: Graphene.ProductComponents.InterstitialScreen

  @doc false
  defdelegate notification(assigns), to: Graphene.ProductComponents.Notification

  @doc false
  defdelegate notification_footer(assigns), to: Graphene.ProductComponents.Notification

  @doc false
  defdelegate notification_panel(assigns), to: Graphene.ProductComponents.Notification

  @doc false
  defdelegate options_tile(assigns), to: Graphene.ProductComponents.OptionsTile

  @doc false
  defdelegate page_header(assigns), to: Graphene.ProductComponents.PageHeader

  @doc false
  defdelegate page_header_breadcrumb(assigns), to: Graphene.ProductComponents.PageHeader

  @doc false
  defdelegate page_header_content(assigns), to: Graphene.ProductComponents.PageHeaderContent

  @doc false
  defdelegate page_header_content_text(assigns), to: Graphene.ProductComponents.PageHeaderContent

  @doc false
  defdelegate page_header_hero_image(assigns), to: Graphene.ProductComponents.PageHeader

  @doc false
  defdelegate page_header_scroller(assigns), to: Graphene.ProductComponents.PageHeader

  @doc false
  defdelegate page_header_tabs(assigns), to: Graphene.ProductComponents.PageHeader

  @doc false
  defdelegate page_header_title_breadcrumb(assigns), to: Graphene.ProductComponents.PageHeader

  @doc false
  defdelegate side_panel(assigns), to: Graphene.ProductComponents.SidePanel

  @doc false
  defdelegate tearsheet(assigns), to: Graphene.ProductComponents.Tearsheet

  @doc false
  defdelegate truncated_text(assigns), to: Graphene.ProductComponents.TruncatedText

  @doc false
  defdelegate user_avatar(assigns), to: Graphene.ProductComponents.UserAvatar
end
